import { type Registry } from "shadcn/schema"

export const styles: Registry["items"] = [
  {
    name: "colors-zinc",
    type: "registry:style",
    cssVars: {
      light: {
        background: "var(--color-white)",
        foreground: "var(--color-zinc-900)",
        card: "var(--color-white)",
        "card-foreground": "var(--color-zinc-900)",
        popover: "var(--color-white)",
        "popover-foreground": "var(--color-zinc-900)",
        primary: "var(--color-zinc-800)",
        "primary-foreground": "var(--color-zinc-50)",
        secondary: "--alpha(var(--color-black) / 4%)",
        "secondary-foreground": "var(--color-zinc-900)",
        muted: "--alpha(var(--color-black) / 4%)",
        "muted-foreground": "var(--color-zinc-600)",
        accent: "--alpha(var(--color-black) / 4%)",
        "accent-foreground": "var(--color-zinc-900)",
        destructive: "var(--color-red-500)",
        "destructive-foreground": "var(--color-red-700)",
        info: "var(--color-blue-500)",
        "info-foreground": "var(--color-blue-700)",
        success: "var(--color-emerald-500)",
        "success-foreground": "var(--color-emerald-700)",
        warning: "var(--color-amber-500)",
        "warning-foreground": "var(--color-amber-700)",
        border: "--alpha(var(--color-black) / 10%)",
        input: "--alpha(var(--color-black) / 10%)",
        ring: "var(--color-zinc-400)",
      },
      dark: {
        background: "var(--color-zinc-950)",
        foreground: "var(--color-zinc-100)",
        card: "color-mix(in srgb, var(--color-zinc-900) 80%, var(--color-zinc-950))",
        "card-foreground": "var(--color-zinc-100)",
        popover: "var(--color-zinc-900)",
        "popover-foreground": "var(--color-zinc-100)",
        primary: "var(--color-zinc-100)",
        "primary-foreground": "var(--color-zinc-900)",
        secondary: "--alpha(var(--color-white) / 8%)",
        "secondary-foreground": "var(--color-zinc-100)",
        muted: "--alpha(var(--color-white) / 8%)",
        "muted-foreground": "var(--color-zinc-400)",
        accent: "--alpha(var(--color-white) / 8%)",
        "accent-foreground": "var(--color-zinc-100)",
        destructive: "var(--color-red-500)",
        "destructive-foreground": "var(--color-red-400)",
        info: "var(--color-blue-500)",
        "info-foreground": "var(--color-blue-400)",
        success: "var(--color-emerald-500)",
        "success-foreground": "var(--color-emerald-400)",
        warning: "var(--color-amber-500)",
        "warning-foreground": "var(--color-amber-400)",
        border: "--alpha(var(--color-white) / 12%)",
        input: "--alpha(var(--color-white) / 12%)",
        ring: "var(--color-zinc-500)",
      },
    },
  },
]
