import type { Registry } from "shadcn/schema";

export const examples: Registry["items"] = [
  {
    categories: ["accordion"],
    description: "Controlled accordion",
    files: [
      {
        path: "examples/accordion-controlled.tsx",
        type: "registry:example",
      },
    ],
    name: "accordion-controlled",
    registryDependencies: ["@coss/accordion", "@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["accordion"],
    description: "Basic accordion",
    files: [
      {
        path: "examples/accordion-demo.tsx",
        type: "registry:example",
      },
    ],
    name: "accordion-demo",
    registryDependencies: ["@coss/accordion"],
    type: "registry:example",
  },
  {
    categories: ["accordion"],
    description: "Accordion allowing multiple panels open",
    files: [
      {
        path: "examples/accordion-multiple.tsx",
        type: "registry:example",
      },
    ],
    name: "accordion-multiple",
    registryDependencies: ["@coss/accordion"],
    type: "registry:example",
  },
  {
    categories: ["accordion"],
    description: "Accordion with one panel open",
    files: [
      {
        path: "examples/accordion-single.tsx",
        type: "registry:example",
      },
    ],
    name: "accordion-single",
    registryDependencies: ["@coss/accordion"],
    type: "registry:example",
  },
  {
    categories: ["alert"],
    description: "Basic alert",
    files: [
      {
        path: "examples/alert-demo.tsx",
        type: "registry:example",
      },
    ],
    name: "alert-demo",
    registryDependencies: ["@coss/alert"],
    type: "registry:example",
  },
  {
    categories: ["alert"],
    description: "Alert with icon",
    files: [
      {
        path: "examples/alert-with-icon.tsx",
        type: "registry:example",
      },
    ],
    name: "alert-with-icon",
    registryDependencies: ["@coss/alert"],
    type: "registry:example",
  },
  {
    categories: ["alert"],
    description: "Alert with icon and action buttons",
    files: [
      {
        path: "examples/alert-with-icon-action.tsx",
        type: "registry:example",
      },
    ],
    name: "alert-with-icon-action",
    registryDependencies: ["@coss/alert", "@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["alert", "info"],
    description: "Info alert",
    files: [
      {
        path: "examples/alert-info.tsx",
        type: "registry:example",
      },
    ],
    name: "alert-info",
    registryDependencies: ["@coss/alert"],
    type: "registry:example",
  },
  {
    categories: ["alert", "success"],
    description: "Success alert",
    files: [
      {
        path: "examples/alert-success.tsx",
        type: "registry:example",
      },
    ],
    name: "alert-success",
    registryDependencies: ["@coss/alert"],
    type: "registry:example",
  },
  {
    categories: ["alert", "warning"],
    description: "Warning alert",
    files: [
      {
        path: "examples/alert-warning.tsx",
        type: "registry:example",
      },
    ],
    name: "alert-warning",
    registryDependencies: ["@coss/alert"],
    type: "registry:example",
  },
  {
    categories: ["alert", "error"],
    description: "Error alert",
    files: [
      {
        path: "examples/alert-error.tsx",
        type: "registry:example",
      },
    ],
    name: "alert-error",
    registryDependencies: ["@coss/alert"],
    type: "registry:example",
  },
  {
    categories: ["dialog"],
    description: "Alert dialog",
    files: [
      {
        path: "examples/alert-dialog-demo.tsx",
        type: "registry:example",
      },
    ],
    name: "alert-dialog-demo",
    registryDependencies: ["@coss/alert-dialog", "@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["autocomplete", "input"],
    description: "Basic autocomplete",
    files: [
      {
        path: "examples/autocomplete-demo.tsx",
        type: "registry:example",
      },
    ],
    name: "autocomplete-demo",
    registryDependencies: ["@coss/autocomplete"],
    type: "registry:example",
  },
  {
    categories: ["autocomplete", "input", "disabled"],
    description: "Disabled autocomplete",
    files: [
      {
        path: "examples/autocomplete-disabled.tsx",
        type: "registry:example",
      },
    ],
    name: "autocomplete-disabled",
    registryDependencies: ["@coss/autocomplete"],
    type: "registry:example",
  },
  {
    categories: ["autocomplete", "input"],
    description: "Small autocomplete",
    files: [
      {
        path: "examples/autocomplete-sm.tsx",
        type: "registry:example",
      },
    ],
    name: "autocomplete-sm",
    registryDependencies: ["@coss/autocomplete"],
    type: "registry:example",
  },
  {
    categories: ["autocomplete", "input"],
    description: "Large autocomplete",
    files: [
      {
        path: "examples/autocomplete-lg.tsx",
        type: "registry:example",
      },
    ],
    name: "autocomplete-lg",
    registryDependencies: ["@coss/autocomplete"],
    type: "registry:example",
  },
  {
    categories: ["autocomplete", "input"],
    description: "Autocomplete with label",
    files: [
      {
        path: "examples/autocomplete-with-label.tsx",
        type: "registry:example",
      },
    ],
    name: "autocomplete-with-label",
    registryDependencies: ["@coss/autocomplete", "@coss/label"],
    type: "registry:example",
  },
  {
    categories: ["autocomplete", "input"],
    description: "Autocomplete autofilling the input with the highlighted item",
    files: [
      {
        path: "examples/autocomplete-inline.tsx",
        type: "registry:example",
      },
    ],
    name: "autocomplete-inline",
    registryDependencies: ["@coss/autocomplete"],
    type: "registry:example",
  },
  {
    categories: ["autocomplete", "input"],
    description: "Autocomplete auto highlighting the first option",
    files: [
      {
        path: "examples/autocomplete-autohighlight.tsx",
        type: "registry:example",
      },
    ],
    name: "autocomplete-autohighlight",
    registryDependencies: ["@coss/autocomplete"],
    type: "registry:example",
  },
  {
    categories: ["autocomplete", "input"],
    description: "Autocomplete with clear button",
    files: [
      {
        path: "examples/autocomplete-with-clear.tsx",
        type: "registry:example",
      },
    ],
    name: "autocomplete-with-clear",
    registryDependencies: ["@coss/autocomplete"],
    type: "registry:example",
  },
  {
    categories: ["autocomplete", "input"],
    description: "Autocomplete with trigger and clear buttons",
    files: [
      {
        path: "examples/autocomplete-with-trigger-clear.tsx",
        type: "registry:example",
      },
    ],
    name: "autocomplete-with-trigger-clear",
    registryDependencies: ["@coss/autocomplete"],
    type: "registry:example",
  },
  {
    categories: ["autocomplete", "input"],
    description: "Autocomplete with grouped items",
    files: [
      {
        path: "examples/autocomplete-grouped.tsx",
        type: "registry:example",
      },
    ],
    name: "autocomplete-grouped",
    registryDependencies: ["@coss/autocomplete"],
    type: "registry:example",
  },
  {
    categories: ["autocomplete", "input"],
    description: "Autocomplete with limited number of results",
    files: [
      {
        path: "examples/autocomplete-limit.tsx",
        type: "registry:example",
      },
    ],
    name: "autocomplete-limit",
    registryDependencies: ["@coss/autocomplete"],
    type: "registry:example",
  },
  {
    categories: ["autocomplete", "input", "async"],
    description: "Autocomplete with async items loading",
    files: [
      {
        path: "examples/autocomplete-async.tsx",
        type: "registry:example",
      },
    ],
    name: "autocomplete-async",
    registryDependencies: ["@coss/autocomplete"],
    type: "registry:example",
  },
  {
    categories: ["autocomplete", "input", "form"],
    description: "Autocomplete form",
    files: [
      {
        path: "examples/autocomplete-form.tsx",
        type: "registry:example",
      },
    ],
    name: "autocomplete-form",
    registryDependencies: ["@coss/autocomplete", "@coss/form", "@coss/field"],
    type: "registry:example",
  },
  {
    categories: ["avatar"],
    description: "Avatar with image and fallback",
    files: [
      {
        path: "examples/avatar-demo.tsx",
        type: "registry:example",
      },
    ],
    name: "avatar-demo",
    registryDependencies: ["@coss/avatar"],
    type: "registry:example",
  },
  {
    categories: ["avatar"],
    description: "Fallback-only avatar",
    files: [
      {
        path: "examples/avatar-fallback.tsx",
        type: "registry:example",
      },
    ],
    name: "avatar-fallback",
    registryDependencies: ["@coss/avatar"],
    type: "registry:example",
  },
  {
    categories: ["avatar", "avatar group"],
    description: "Overlapping avatar group",
    files: [
      {
        path: "examples/avatar-group.tsx",
        type: "registry:example",
      },
    ],
    name: "avatar-group",
    registryDependencies: ["@coss/avatar"],
    type: "registry:example",
  },
  {
    categories: ["avatar"],
    description: "Avatars with different radii",
    files: [
      {
        path: "examples/avatar-radius.tsx",
        type: "registry:example",
      },
    ],
    name: "avatar-radius",
    registryDependencies: ["@coss/avatar"],
    type: "registry:example",
  },
  {
    categories: ["avatar"],
    description: "Avatars with different sizes",
    files: [
      {
        path: "examples/avatar-size.tsx",
        type: "registry:example",
      },
    ],
    name: "avatar-size",
    registryDependencies: ["@coss/avatar"],
    type: "registry:example",
  },
  {
    categories: ["badge"],
    description: "Basic badge",
    files: [
      {
        path: "examples/badge-demo.tsx",
        type: "registry:example",
      },
    ],
    name: "badge-demo",
    registryDependencies: ["@coss/badge"],
    type: "registry:example",
  },
  {
    categories: ["badge"],
    description: "Outline badge",
    files: [
      {
        path: "examples/badge-outline.tsx",
        type: "registry:example",
      },
    ],
    name: "badge-outline",
    registryDependencies: ["@coss/badge"],
    type: "registry:example",
  },
  {
    categories: ["badge"],
    description: "Secondary badge",
    files: [
      {
        path: "examples/badge-secondary.tsx",
        type: "registry:example",
      },
    ],
    name: "badge-secondary",
    registryDependencies: ["@coss/badge"],
    type: "registry:example",
  },
  {
    categories: ["badge", "destructive", "error"],
    description: "Destructive badge",
    files: [
      {
        path: "examples/badge-destructive.tsx",
        type: "registry:example",
      },
    ],
    name: "badge-destructive",
    registryDependencies: ["@coss/badge"],
    type: "registry:example",
  },
  {
    categories: ["badge", "info"],
    description: "Info badge",
    files: [
      {
        path: "examples/badge-info.tsx",
        type: "registry:example",
      },
    ],
    name: "badge-info",
    registryDependencies: ["@coss/badge"],
    type: "registry:example",
  },
  {
    categories: ["badge", "success"],
    description: "Success badge",
    files: [
      {
        path: "examples/badge-success.tsx",
        type: "registry:example",
      },
    ],
    name: "badge-success",
    registryDependencies: ["@coss/badge"],
    type: "registry:example",
  },
  {
    categories: ["badge", "warning"],
    description: "Warning badge",
    files: [
      {
        path: "examples/badge-warning.tsx",
        type: "registry:example",
      },
    ],
    name: "badge-warning",
    registryDependencies: ["@coss/badge"],
    type: "registry:example",
  },
  {
    categories: ["badge", "error"],
    description: "Error badge",
    files: [
      {
        path: "examples/badge-error.tsx",
        type: "registry:example",
      },
    ],
    name: "badge-error",
    registryDependencies: ["@coss/badge"],
    type: "registry:example",
  },
  {
    categories: ["badge"],
    description: "Small badge",
    files: [
      {
        path: "examples/badge-sm.tsx",
        type: "registry:example",
      },
    ],
    name: "badge-sm",
    registryDependencies: ["@coss/badge"],
    type: "registry:example",
  },
  {
    categories: ["badge"],
    description: "Large badge",
    files: [
      {
        path: "examples/badge-lg.tsx",
        type: "registry:example",
      },
    ],
    name: "badge-lg",
    registryDependencies: ["@coss/badge"],
    type: "registry:example",
  },
  {
    categories: ["badge"],
    description: "Badge with icon",
    files: [
      {
        path: "examples/badge-with-icon.tsx",
        type: "registry:example",
      },
    ],
    name: "badge-with-icon",
    registryDependencies: ["@coss/badge"],
    type: "registry:example",
  },
  {
    categories: ["badge"],
    description: "Badge with link",
    files: [
      {
        path: "examples/badge-with-link.tsx",
        type: "registry:example",
      },
    ],
    name: "badge-with-link",
    registryDependencies: ["@coss/badge"],
    type: "registry:example",
  },
  {
    categories: ["breadcrumb", "menu"],
    description: "Breadcrumb with menu example",
    files: [{ path: "examples/breadcrumb-demo.tsx", type: "registry:example" }],
    name: "breadcrumb-demo",
    registryDependencies: ["@coss/breadcrumb", "@coss/menu"],
    type: "registry:example",
  },
  {
    categories: ["breadcrumb"],
    description: "Breadcrumb with custom separator",
    files: [
      {
        path: "examples/breadcrumb-custom-separator.tsx",
        type: "registry:example",
      },
    ],
    name: "breadcrumb-custom-separator",
    registryDependencies: ["@coss/breadcrumb"],
    type: "registry:example",
  },
  {
    categories: ["button"],
    description: "Default button",
    files: [
      {
        path: "examples/button-demo.tsx",
        type: "registry:example",
      },
    ],
    name: "button-demo",
    registryDependencies: ["@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["button"],
    description: "Secondary button",
    files: [
      {
        path: "examples/button-secondary.tsx",
        type: "registry:example",
      },
    ],
    name: "button-secondary",
    registryDependencies: ["@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["button", "delete", "destructive"],
    description: "Destructive button",
    files: [
      {
        path: "examples/button-destructive.tsx",
        type: "registry:example",
      },
    ],
    name: "button-destructive",
    registryDependencies: ["@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["button", "delete"],
    description: "Destructive outline button",
    files: [
      {
        path: "examples/button-destructive-outline.tsx",
        type: "registry:example",
      },
    ],
    name: "button-destructive-outline",
    registryDependencies: ["@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["button"],
    description: "Outline button",
    files: [{ path: "examples/button-outline.tsx", type: "registry:example" }],
    name: "button-outline",
    registryDependencies: ["@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["button"],
    description: "Ghost button",
    files: [{ path: "examples/button-ghost.tsx", type: "registry:example" }],
    name: "button-ghost",
    registryDependencies: ["@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["button"],
    description: "Link button",
    files: [{ path: "examples/button-link.tsx", type: "registry:example" }],
    name: "button-link",
    registryDependencies: ["@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["button"],
    description: "Extra-small button",
    files: [{ path: "examples/button-xs.tsx", type: "registry:example" }],
    name: "button-xs",
    registryDependencies: ["@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["button"],
    description: "Small button",
    files: [{ path: "examples/button-sm.tsx", type: "registry:example" }],
    name: "button-sm",
    registryDependencies: ["@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["button"],
    description: "Large button",
    files: [{ path: "examples/button-lg.tsx", type: "registry:example" }],
    name: "button-lg",
    registryDependencies: ["@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["button"],
    description: "Extra-large button",
    files: [{ path: "examples/button-xl.tsx", type: "registry:example" }],
    name: "button-xl",
    registryDependencies: ["@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["button", "disabled"],
    description: "Disabled button",
    files: [{ path: "examples/button-disabled.tsx", type: "registry:example" }],
    name: "button-disabled",
    registryDependencies: ["@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["button"],
    description: "Icon button",
    files: [{ path: "examples/button-icon.tsx", type: "registry:example" }],
    name: "button-icon",
    registryDependencies: ["@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["button"],
    description: "Small icon button",
    files: [{ path: "examples/button-icon-sm.tsx", type: "registry:example" }],
    name: "button-icon-sm",
    registryDependencies: ["@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["button"],
    description: "Large icon button",
    files: [{ path: "examples/button-icon-lg.tsx", type: "registry:example" }],
    name: "button-icon-lg",
    registryDependencies: ["@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["button"],
    description: "Button with icon",
    files: [
      { path: "examples/button-with-icon.tsx", type: "registry:example" },
    ],
    name: "button-with-icon",
    registryDependencies: ["@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["button"],
    description: "Link rendered as button",
    files: [
      { path: "examples/button-with-link.tsx", type: "registry:example" },
    ],
    name: "button-with-link",
    registryDependencies: ["@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["button", "loading"],
    description: "Loading button",
    files: [{ path: "examples/button-loading.tsx", type: "registry:example" }],
    name: "button-loading",
    registryDependencies: ["@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["card", "button", "input", "select", "form", "field"],
    description: "Card example with form",
    files: [
      {
        path: "examples/card-demo.tsx",
        type: "registry:example",
      },
    ],
    name: "card-demo",
    registryDependencies: [
      "@coss/card",
      "@coss/button",
      "@coss/select",
      "@coss/form",
      "@coss/field",
      "@coss/input",
    ],
    type: "registry:example",
  },
  {
    categories: ["checkbox", "card", "label"],
    description: "Card-style checkbox",
    files: [{ path: "examples/checkbox-card.tsx", type: "registry:example" }],
    name: "checkbox-card",
    registryDependencies: ["@coss/checkbox", "@coss/label"],
    type: "registry:example",
  },
  {
    categories: ["checkbox", "label"],
    description: "Basic checkbox",
    files: [{ path: "examples/checkbox-demo.tsx", type: "registry:example" }],
    name: "checkbox-demo",
    registryDependencies: ["@coss/checkbox", "@coss/label"],
    type: "registry:example",
  },
  {
    categories: ["checkbox", "disabled", "label"],
    description: "Disabled checkbox",
    files: [
      { path: "examples/checkbox-disabled.tsx", type: "registry:example" },
    ],
    name: "checkbox-disabled",
    registryDependencies: ["@coss/checkbox", "@coss/label"],
    type: "registry:example",
  },
  {
    categories: ["checkbox", "form", "button", "label"],
    description: "Checkbox in a form",
    files: [{ path: "examples/checkbox-form.tsx", type: "registry:example" }],
    name: "checkbox-form",
    registryDependencies: [
      "@coss/checkbox",
      "@coss/field",
      "@coss/form",
      "@coss/button",
    ],
    type: "registry:example",
  },
  {
    categories: ["checkbox group", "checkbox"],
    description: "Checkbox group",
    files: [
      { path: "examples/checkbox-group-demo.tsx", type: "registry:example" },
    ],
    name: "checkbox-group-demo",
    registryDependencies: [
      "@coss/checkbox-group",
      "@coss/checkbox",
      "@coss/label",
    ],
    type: "registry:example",
  },
  {
    categories: ["checkbox group", "checkbox", "disabled"],
    description: "Checkbox group with disabled item",
    files: [
      {
        path: "examples/checkbox-group-disabled.tsx",
        type: "registry:example",
      },
    ],
    name: "checkbox-group-disabled",
    registryDependencies: [
      "@coss/checkbox-group",
      "@coss/checkbox",
      "@coss/label",
    ],
    type: "registry:example",
  },
  {
    categories: [
      "checkbox group",
      "checkbox",
      "form",
      "button",
      "field",
      "fieldset",
    ],
    description: "Checkbox group in a form",
    files: [
      { path: "examples/checkbox-group-form.tsx", type: "registry:example" },
    ],
    name: "checkbox-group-form",
    registryDependencies: [
      "@coss/checkbox-group",
      "@coss/checkbox",
      "@coss/button",
      "@coss/field",
      "@coss/fieldset",
      "@coss/form",
    ],
    type: "registry:example",
  },
  {
    categories: ["checkbox group", "checkbox", "label"],
    description: "Checkbox group parent with nested children controls",
    files: [
      {
        path: "examples/checkbox-group-nested-parent.tsx",
        type: "registry:example",
      },
    ],
    name: "checkbox-group-nested-parent",
    registryDependencies: [
      "@coss/checkbox-group",
      "@coss/checkbox",
      "@coss/label",
    ],
    type: "registry:example",
  },
  {
    categories: ["checkbox group", "checkbox", "label"],
    description: "Checkbox group select/deselect all checkboxes",
    files: [
      { path: "examples/checkbox-group-parent.tsx", type: "registry:example" },
    ],
    name: "checkbox-group-parent",
    registryDependencies: [
      "@coss/checkbox-group",
      "@coss/checkbox",
      "@coss/label",
    ],
    type: "registry:example",
  },
  {
    categories: ["checkbox", "label", "helper", "hint"],
    description: "Checkbox with helper text",
    files: [
      {
        path: "examples/checkbox-with-description.tsx",
        type: "registry:example",
      },
    ],
    name: "checkbox-with-description",
    registryDependencies: ["@coss/checkbox", "@coss/label"],
    type: "registry:example",
  },
  {
    categories: ["collapsible"],
    description: "Basic collapsible",
    files: [
      { path: "examples/collapsible-demo.tsx", type: "registry:example" },
    ],
    name: "collapsible-demo",
    registryDependencies: ["@coss/collapsible"],
    type: "registry:example",
  },
  {
    categories: ["combobox", "input"],
    description: "Basic combobox",
    files: [{ path: "examples/combobox-demo.tsx", type: "registry:example" }],
    name: "combobox-demo",
    registryDependencies: ["@coss/combobox"],
    type: "registry:example",
  },
  {
    categories: ["combobox", "input", "disabled"],
    description: "Disabled combobox",
    files: [
      { path: "examples/combobox-disabled.tsx", type: "registry:example" },
    ],
    name: "combobox-disabled",
    registryDependencies: ["@coss/combobox"],
    type: "registry:example",
  },
  {
    categories: ["combobox", "input"],
    description: "Small combobox",
    files: [{ path: "examples/combobox-sm.tsx", type: "registry:example" }],
    name: "combobox-sm",
    registryDependencies: ["@coss/combobox"],
    type: "registry:example",
  },
  {
    categories: ["combobox", "input"],
    description: "Large combobox",
    files: [{ path: "examples/combobox-lg.tsx", type: "registry:example" }],
    name: "combobox-lg",
    registryDependencies: ["@coss/combobox"],
    type: "registry:example",
  },
  {
    categories: ["combobox", "input"],
    description: "Combobox with label",
    files: [
      { path: "examples/combobox-with-label.tsx", type: "registry:example" },
    ],
    name: "combobox-with-label",
    registryDependencies: ["@coss/combobox", "@coss/label"],
    type: "registry:example",
  },
  {
    categories: ["combobox", "input"],
    description: "Combobox auto highlighting the first option",
    files: [
      { path: "examples/combobox-autohighlight.tsx", type: "registry:example" },
    ],
    name: "combobox-autohighlight",
    registryDependencies: ["@coss/combobox"],
    type: "registry:example",
  },
  {
    categories: ["combobox", "input"],
    description: "Combobox with grouped items",
    files: [
      { path: "examples/combobox-grouped.tsx", type: "registry:example" },
    ],
    name: "combobox-grouped",
    registryDependencies: ["@coss/combobox"],
    type: "registry:example",
  },
  {
    categories: ["combobox", "input"],
    description: "Combobox with clear button",
    files: [
      { path: "examples/combobox-with-clear.tsx", type: "registry:example" },
    ],
    name: "combobox-with-clear",
    registryDependencies: ["@coss/combobox"],
    type: "registry:example",
  },
  {
    categories: ["combobox", "input"],
    description: "Combobox with multiple selection",
    files: [
      { path: "examples/combobox-multiple.tsx", type: "registry:example" },
    ],
    name: "combobox-multiple",
    registryDependencies: ["@coss/combobox"],
    type: "registry:example",
  },
  {
    categories: ["combobox", "input"],
    description: "Combobox with popup",
    files: [
      {
        path: "examples/combobox-with-inner-input.tsx",
        type: "registry:example",
      },
    ],
    name: "combobox-with-inner-input",
    registryDependencies: ["@coss/combobox", "@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["combobox", "input", "form"],
    description: "Combobox form",
    files: [{ path: "examples/combobox-form.tsx", type: "registry:example" }],
    name: "combobox-form",
    registryDependencies: [
      "@coss/combobox",
      "@coss/button",
      "@coss/form",
      "@coss/field",
    ],
    type: "registry:example",
  },
  {
    categories: ["combobox", "input", "form", "multiple"],
    description: "Combobox multiple selection form",
    files: [
      { path: "examples/combobox-multiple-form.tsx", type: "registry:example" },
    ],
    name: "combobox-multiple-form",
    registryDependencies: [
      "@coss/combobox",
      "@coss/button",
      "@coss/form",
      "@coss/field",
    ],
    type: "registry:example",
  },
  {
    categories: [
      "dialog",
      "alert dialog",
      "form",
      "field",
      "button",
      "textarea",
    ],
    description: "Prompt before closing with unsaved changes",
    files: [
      {
        path: "examples/dialog-close-confirmation.tsx",
        type: "registry:example",
      },
    ],
    name: "dialog-close-confirmation",
    registryDependencies: [
      "@coss/alert-dialog",
      "@coss/dialog",
      "@coss/button",
      "@coss/form",
      "@coss/field",
      "@coss/textarea",
    ],
    type: "registry:example",
  },
  {
    categories: ["dialog", "form", "field", "button"],
    description: "Basic dialog",
    files: [{ path: "examples/dialog-demo.tsx", type: "registry:example" }],
    name: "dialog-demo",
    registryDependencies: [
      "@coss/dialog",
      "@coss/button",
      "@coss/form",
      "@coss/field",
      "@coss/input",
    ],
    type: "registry:example",
  },
  {
    categories: ["dialog", "menu", "button"],
    description: "Open dialog from a menu item",
    files: [
      { path: "examples/dialog-from-menu.tsx", type: "registry:example" },
    ],
    name: "dialog-from-menu",
    registryDependencies: ["@coss/dialog", "@coss/menu", "@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["dialog", "field", "button"],
    description: "Dialog with a nested dialog",
    files: [{ path: "examples/dialog-nested.tsx", type: "registry:example" }],
    name: "dialog-nested",
    registryDependencies: [
      "@coss/dialog",
      "@coss/button",
      "@coss/field",
      "@coss/input",
    ],
    type: "registry:example",
  },
  {
    categories: ["sheet", "dialog"],
    description: "Basic sheet",
    files: [{ path: "examples/sheet-demo.tsx", type: "registry:example" }],
    name: "sheet-demo",
    registryDependencies: [
      "@coss/sheet",
      "@coss/button",
      "@coss/form",
      "@coss/field",
      "@coss/input",
    ],
    type: "registry:example",
  },
  {
    categories: ["sheet"],
    description: "Sheet inset",
    files: [{ path: "examples/sheet-inset.tsx", type: "registry:example" }],
    name: "sheet-inset",
    registryDependencies: [
      "@coss/sheet",
      "@coss/button",
      "@coss/form",
      "@coss/field",
      "@coss/input",
    ],
    type: "registry:example",
  },
  {
    categories: ["sheet"],
    description: "Sheet position",
    files: [{ path: "examples/sheet-position.tsx", type: "registry:example" }],
    name: "sheet-position",
    registryDependencies: ["@coss/sheet", "@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["field", "label", "checkbox"],
    description: "Field with checkbox",
    files: [{ path: "examples/field-checkbox.tsx", type: "registry:example" }],
    name: "field-checkbox",
    registryDependencies: ["@coss/field", "@coss/checkbox"],
    type: "registry:example",
  },
  {
    categories: ["field", "checkbox group", "checkbox", "fieldset", "label"],
    description: "Field with checkbox group",
    files: [
      { path: "examples/field-checkbox-group.tsx", type: "registry:example" },
    ],
    name: "field-checkbox-group",
    registryDependencies: [
      "@coss/field",
      "@coss/checkbox-group",
      "@coss/checkbox",
      "@coss/fieldset",
    ],
    type: "registry:example",
  },
  {
    categories: [
      "field",
      "label",
      "form",
      "select",
      "checkbox",
      "button",
      "helper",
      "hint",
    ],
    description: "Complete form built with field",
    files: [
      { path: "examples/field-complete-form.tsx", type: "registry:example" },
    ],
    name: "field-complete-form",
    registryDependencies: [
      "@coss/field",
      "@coss/select",
      "@coss/checkbox",
      "@coss/form",
      "@coss/input",
      "@coss/button",
    ],
    type: "registry:example",
  },
  {
    categories: ["field", "label", "helper", "hint"],
    description: "Field with description",
    files: [{ path: "examples/field-demo.tsx", type: "registry:example" }],
    name: "field-demo",
    registryDependencies: ["@coss/field", "@coss/input"],
    type: "registry:example",
  },
  {
    categories: ["field", "label", "disabled", "helper", "hint"],
    description: "Field in disabled state",
    files: [{ path: "examples/field-disabled.tsx", type: "registry:example" }],
    name: "field-disabled",
    registryDependencies: ["@coss/field", "@coss/input"],
    type: "registry:example",
  },
  {
    categories: ["field", "label", "error"],
    description: "Field showing validation error",
    files: [{ path: "examples/field-error.tsx", type: "registry:example" }],
    name: "field-error",
    registryDependencies: ["@coss/field", "@coss/input"],
    type: "registry:example",
  },
  {
    categories: ["field", "input", "autocomplete", "label"],
    description: "Field with autocomplete",
    files: [
      { path: "examples/field-autocomplete.tsx", type: "registry:example" },
    ],
    name: "field-autocomplete",
    registryDependencies: ["@coss/field", "@coss/autocomplete"],
    type: "registry:example",
  },
  {
    categories: ["field", "input", "combobox", "label"],
    description: "Field with combobox",
    files: [{ path: "examples/field-combobox.tsx", type: "registry:example" }],
    name: "field-combobox",
    registryDependencies: ["@coss/field", "@coss/combobox"],
    type: "registry:example",
  },
  {
    categories: ["field", "input", "combobox", "label", "multiple"],
    description: "Field with multiple selection combobox",
    files: [
      {
        path: "examples/field-combobox-multiple.tsx",
        type: "registry:example",
      },
    ],
    name: "field-combobox-multiple",
    registryDependencies: ["@coss/field", "@coss/combobox"],
    type: "registry:example",
  },
  {
    categories: ["field", "input", "label", "number", "helper", "hint"],
    description: "Field with number field",
    files: [
      { path: "examples/field-number-field.tsx", type: "registry:example" },
    ],
    name: "field-number-field",
    registryDependencies: ["@coss/field", "@coss/number-field"],
    type: "registry:example",
  },
  {
    categories: ["field", "radio", "label", "fieldset", "helper", "hint"],
    description: "Field with radio group",
    files: [{ path: "examples/field-radio.tsx", type: "registry:example" }],
    name: "field-radio",
    registryDependencies: [
      "@coss/field",
      "@coss/radio-group",
      "@coss/fieldset",
    ],
    type: "registry:example",
  },
  {
    categories: ["field", "label", "required"],
    description: "Field with required indicator",
    files: [{ path: "examples/field-required.tsx", type: "registry:example" }],
    name: "field-required",
    registryDependencies: ["@coss/field", "@coss/input"],
    type: "registry:example",
  },
  {
    categories: ["field", "select", "label", "helper", "hint"],
    description: "Field with select",
    files: [{ path: "examples/field-select.tsx", type: "registry:example" }],
    name: "field-select",
    registryDependencies: ["@coss/field", "@coss/select"],
    type: "registry:example",
  },
  {
    categories: ["field", "slider", "label", "helper", "hint"],
    description: "Field with slider",
    files: [{ path: "examples/field-slider.tsx", type: "registry:example" }],
    name: "field-slider",
    registryDependencies: ["@coss/field", "@coss/slider"],
    type: "registry:example",
  },
  {
    categories: ["field", "switch", "label"],
    description: "Field with toggle switch",
    files: [{ path: "examples/field-switch.tsx", type: "registry:example" }],
    name: "field-switch",
    registryDependencies: ["@coss/field", "@coss/switch"],
    type: "registry:example",
  },
  {
    categories: ["field", "textarea", "label", "helper", "hint"],
    description: "Field with textarea",
    files: [{ path: "examples/field-textarea.tsx", type: "registry:example" }],
    name: "field-textarea",
    registryDependencies: ["@coss/field", "@coss/textarea"],
    type: "registry:example",
  },
  {
    categories: ["field"],
    description: "Show field validity state",
    files: [{ path: "examples/field-validity.tsx", type: "registry:example" }],
    name: "field-validity",
    registryDependencies: ["@coss/field", "@coss/input"],
    type: "registry:example",
  },
  {
    categories: ["fieldset", "field", "label", "input", "helper"],
    description: "Fieldset with legend and labeled fields",
    files: [{ path: "examples/fieldset-demo.tsx", type: "registry:example" }],
    name: "fieldset-demo",
    registryDependencies: ["@coss/fieldset", "@coss/field", "@coss/input"],
    type: "registry:example",
  },
  {
    categories: ["form", "field", "button", "input"],
    description: "Input in a form",
    files: [
      {
        path: "examples/form-demo.tsx",
        type: "registry:example",
      },
    ],
    name: "form-demo",
    registryDependencies: [
      "@coss/form",
      "@coss/field",
      "@coss/button",
      "@coss/input",
    ],
    type: "registry:example",
  },
  {
    categories: ["form", "field", "button", "validation", "label", "zod"],
    dependencies: ["zod"],
    description: "Form with zod validation",
    files: [{ path: "examples/form-zod.tsx", type: "registry:example" }],
    name: "form-zod",
    registryDependencies: [
      "@coss/form",
      "@coss/field",
      "@coss/button",
      "@coss/input",
    ],
    type: "registry:example",
  },
  {
    categories: ["empty"],
    description: "Basic empty state with icon",
    files: [{ path: "examples/empty-demo.tsx", type: "registry:example" }],
    name: "empty-demo",
    registryDependencies: ["@coss/empty", "@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["input"],
    description: "Basic input component without label",
    files: [
      {
        path: "examples/input-demo.tsx",
        type: "registry:example",
      },
    ],
    name: "input-demo",
    registryDependencies: ["@coss/input"],
    type: "registry:example",
  },
  {
    categories: ["frame"],
    description: "Frame example",
    files: [{ path: "examples/frame-demo.tsx", type: "registry:example" }],
    name: "frame-demo",
    registryDependencies: ["@coss/frame"],
    type: "registry:example",
  },
  {
    categories: ["group"],
    description: "Group example",
    files: [{ path: "examples/group-demo.tsx", type: "registry:example" }],
    name: "group-demo",
    registryDependencies: ["@coss/group", "@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["group", "input", "copy", "button", "tooltip"],
    description: "Group with input and copy button",
    files: [
      { path: "examples/group-with-input.tsx", type: "registry:example" },
    ],
    name: "group-with-input",
    registryDependencies: [
      "@coss/group",
      "@coss/button",
      "@coss/input",
      "@coss/tooltip",
    ],
    type: "registry:example",
  },
  {
    categories: ["group", "button", "menu"],
    description: "Group with small buttons",
    files: [{ path: "examples/group-sm.tsx", type: "registry:example" }],
    name: "group-sm",
    registryDependencies: ["@coss/group", "@coss/button", "@coss/menu"],
    type: "registry:example",
  },
  {
    categories: ["group", "button", "menu"],
    description: "Group with large buttons",
    files: [{ path: "examples/group-lg.tsx", type: "registry:example" }],
    name: "group-lg",
    registryDependencies: ["@coss/group", "@coss/button", "@coss/menu"],
    type: "registry:example",
  },
  {
    categories: ["group", "button", "menu"],
    description: "Group with disabled button",
    files: [
      {
        path: "examples/group-with-disabled-button.tsx",
        type: "registry:example",
      },
    ],
    name: "group-with-disabled-button",
    registryDependencies: ["@coss/group", "@coss/button", "@coss/menu"],
    type: "registry:example",
  },
  {
    categories: ["group", "button", "menu"],
    description: "Group with default style buttons",
    files: [
      { path: "examples/group-default-button.tsx", type: "registry:example" },
    ],
    name: "group-default-button",
    registryDependencies: ["@coss/group", "@coss/button", "@coss/menu"],
    type: "registry:example",
  },
  {
    categories: ["group", "input", "label"],
    description: "Group with start labeled text",
    files: [{ path: "examples/group-with-text.tsx", type: "registry:example" }],
    name: "group-with-text",
    registryDependencies: ["@coss/group", "@coss/input", "@coss/label"],
    type: "registry:example",
  },
  {
    categories: ["group", "input"],
    description: "Group with end text",
    files: [
      { path: "examples/group-with-end-text.tsx", type: "registry:example" },
    ],
    name: "group-with-end-text",
    registryDependencies: ["@coss/group", "@coss/input"],
    type: "registry:example",
  },
  {
    categories: ["group", "button"],
    description: "Vertical group of buttons",
    files: [{ path: "examples/group-vertical.tsx", type: "registry:example" }],
    name: "group-vertical",
    registryDependencies: ["@coss/group", "@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["group", "button"],
    description: "Pagination example made with nested groups",
    files: [{ path: "examples/group-nested.tsx", type: "registry:example" }],
    name: "group-nested",
    registryDependencies: ["@coss/group", "@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["group", "button", "popover", "badge"],
    description: "Group with button and popup",
    files: [{ path: "examples/group-popup.tsx", type: "registry:example" }],
    name: "group-popup",
    registryDependencies: [
      "@coss/group",
      "@coss/button",
      "@coss/popover",
      "@coss/badge",
    ],
    type: "registry:example",
  },
  {
    categories: ["group", "button", "input", "input group", "tooltip"],
    description: "Nested groups with input group",
    files: [
      { path: "examples/group-input-group.tsx", type: "registry:example" },
    ],
    name: "group-input-group",
    registryDependencies: [
      "@coss/group",
      "@coss/button",
      "@coss/input-group",
      "@coss/tooltip",
    ],
    type: "registry:example",
  },
  {
    categories: ["group", "button", "menu"],
    description: "Group with button and menu",
    files: [{ path: "examples/group-menu.tsx", type: "registry:example" }],
    name: "group-menu",
    registryDependencies: ["@coss/group", "@coss/button", "@coss/menu"],
    type: "registry:example",
  },
  {
    categories: ["group", "select", "number field", "button"],
    description: "Group with select and number field",
    files: [{ path: "examples/group-select.tsx", type: "registry:example" }],
    name: "group-select",
    registryDependencies: [
      "@coss/group",
      "@coss/select",
      "@coss/number-field",
      "@coss/button",
    ],
    type: "registry:example",
  },
  {
    categories: ["input"],
    description: "Small input",
    files: [{ path: "examples/input-sm.tsx", type: "registry:example" }],
    name: "input-sm",
    registryDependencies: ["@coss/input"],
    type: "registry:example",
  },
  {
    categories: ["input"],
    description: "Large input",
    files: [{ path: "examples/input-lg.tsx", type: "registry:example" }],
    name: "input-lg",
    registryDependencies: ["@coss/input"],
    type: "registry:example",
  },
  {
    categories: ["input", "disabled"],
    description: "Input with disabled state",
    files: [
      {
        path: "examples/input-disabled.tsx",
        type: "registry:example",
      },
    ],
    name: "input-disabled",
    registryDependencies: ["@coss/input"],
    type: "registry:example",
  },
  {
    categories: ["input", "file"],
    description: "Input type set to file",
    files: [
      {
        path: "examples/input-file.tsx",
        type: "registry:example",
      },
    ],
    name: "input-file",
    registryDependencies: ["@coss/input"],
    type: "registry:example",
  },
  {
    categories: ["input", "label"],
    description: "Input with label",
    files: [
      {
        path: "examples/input-with-label.tsx",
        type: "registry:example",
      },
    ],
    name: "input-with-label",
    registryDependencies: ["@coss/input", "@coss/label"],
    type: "registry:example",
  },
  {
    categories: ["input", "button"],
    description: "Input with button",
    files: [
      {
        path: "examples/input-with-button.tsx",
        type: "registry:example",
      },
    ],
    name: "input-with-button",
    registryDependencies: ["@coss/input", "@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["input", "input group"],
    description: "Basic input group with search icon",
    files: [
      {
        path: "examples/input-group-demo.tsx",
        type: "registry:example",
      },
    ],
    name: "input-group-demo",
    registryDependencies: ["@coss/input-group"],
    type: "registry:example",
  },
  {
    categories: ["input", "input group"],
    description: "Small input group",
    files: [
      {
        path: "examples/input-group-sm.tsx",
        type: "registry:example",
      },
    ],
    name: "input-group-sm",
    registryDependencies: ["@coss/input-group"],
    type: "registry:example",
  },
  {
    categories: ["input", "input group"],
    description: "Large input group",
    files: [
      {
        path: "examples/input-group-lg.tsx",
        type: "registry:example",
      },
    ],
    name: "input-group-lg",
    registryDependencies: ["@coss/input-group"],
    type: "registry:example",
  },
  {
    categories: ["input", "input group", "disabled", "button"],
    description: "Input group with disabled state",
    files: [
      {
        path: "examples/input-group-disabled.tsx",
        type: "registry:example",
      },
    ],
    name: "input-group-disabled",
    registryDependencies: ["@coss/button", "@coss/input-group"],
    type: "registry:example",
  },
  {
    categories: ["input", "input group", "field", "button"],
    description: "Input group with field",
    files: [
      {
        path: "examples/field-input-group.tsx",
        type: "registry:example",
      },
    ],
    name: "field-input-group",
    registryDependencies: ["@coss/field", "@coss/button", "@coss/input-group"],
    type: "registry:example",
  },
  {
    categories: ["input", "input group", "loading", "spinner"],
    description: "Input group with end loading state",
    files: [
      {
        path: "examples/input-group-loading.tsx",
        type: "registry:example",
      },
    ],
    name: "input-group-loading",
    registryDependencies: ["@coss/input-group", "@coss/spinner"],
    type: "registry:example",
  },
  {
    categories: ["input group", "textarea", "button", "menu", "tooltip"],
    description: "Input group with textarea",
    files: [
      {
        path: "examples/input-group-textarea.tsx",
        type: "registry:example",
      },
    ],
    name: "input-group-textarea",
    registryDependencies: [
      "@coss/input-group",
      "@coss/button",
      "@coss/menu",
      "@coss/tooltip",
    ],
    type: "registry:example",
  },
  {
    categories: ["input", "input group", "badge"],
    description: "Input group with badge",
    files: [
      {
        path: "examples/input-group-with-badge.tsx",
        type: "registry:example",
      },
    ],
    name: "input-group-with-badge",
    registryDependencies: ["@coss/input-group", "@coss/badge"],
    type: "registry:example",
  },
  {
    categories: ["input", "input group", "button"],
    description: "Input group with button",
    files: [
      {
        path: "examples/input-group-with-button.tsx",
        type: "registry:example",
      },
    ],
    name: "input-group-with-button",
    registryDependencies: ["@coss/input-group", "@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["input", "input group"],
    description: "Input group with end icon",
    files: [
      {
        path: "examples/input-group-with-end-icon.tsx",
        type: "registry:example",
      },
    ],
    name: "input-group-with-end-icon",
    registryDependencies: ["@coss/input-group"],
    type: "registry:example",
  },
  {
    categories: ["input", "input group"],
    description: "Input group with end text",
    files: [
      {
        path: "examples/input-group-with-end-text.tsx",
        type: "registry:example",
      },
    ],
    name: "input-group-with-end-text",
    registryDependencies: ["@coss/input-group"],
    type: "registry:example",
  },
  {
    categories: ["input", "input group", "popover", "tooltip"],
    description: "Input group with end tooltip",
    files: [
      {
        path: "examples/input-group-with-end-tooltip.tsx",
        type: "registry:example",
      },
    ],
    name: "input-group-with-end-tooltip",
    registryDependencies: [
      "@coss/input-group",
      "@coss/button",
      "@coss/popover",
    ],
    type: "registry:example",
  },
  {
    categories: ["input", "input group", "button", "tooltip"],
    description: "Input group with copy button",
    files: [
      {
        path: "examples/input-group-with-icon-button.tsx",
        type: "registry:example",
      },
    ],
    name: "input-group-with-icon-button",
    registryDependencies: [
      "@coss/use-copy-to-clipboard",
      "@coss/input-group",
      "@coss/button",
      "@coss/tooltip",
    ],
    type: "registry:example",
  },
  {
    categories: ["input", "input group", "label", "popover", "tooltip"],
    description: "Input group with inner label",
    files: [
      {
        path: "examples/input-group-with-inner-label.tsx",
        type: "registry:example",
      },
    ],
    name: "input-group-with-inner-label",
    registryDependencies: [
      "@coss/input-group",
      "@coss/button",
      "@coss/label",
      "@coss/popover",
    ],
    type: "registry:example",
  },
  {
    categories: ["input", "input group", "kbd", "search"],
    description: "Input group with keyboard shortcut",
    files: [
      {
        path: "examples/input-group-with-kbd.tsx",
        type: "registry:example",
      },
    ],
    name: "input-group-with-kbd",
    registryDependencies: ["@coss/input-group", "@coss/kbd"],
    type: "registry:example",
  },
  {
    categories: ["input", "input group", "number field"],
    description: "Input group with number field",
    files: [
      {
        path: "examples/input-group-with-number-field.tsx",
        type: "registry:example",
      },
    ],
    name: "input-group-with-number-field",
    registryDependencies: ["@coss/input-group", "@coss/number-field"],
    type: "registry:example",
  },
  {
    categories: ["input", "input group"],
    description: "Input group with start and end text",
    files: [
      {
        path: "examples/input-group-with-start-end-text.tsx",
        type: "registry:example",
      },
    ],
    name: "input-group-with-start-end-text",
    registryDependencies: ["@coss/input-group"],
    type: "registry:example",
  },
  {
    categories: ["input", "input group"],
    description: "Input group with start text",
    files: [
      {
        path: "examples/input-group-with-start-text.tsx",
        type: "registry:example",
      },
    ],
    name: "input-group-with-start-text",
    registryDependencies: ["@coss/input-group"],
    type: "registry:example",
  },
  {
    categories: ["kbd"],
    description: "Keyboard shortcuts",
    files: [{ path: "examples/kbd-demo.tsx", type: "registry:example" }],
    name: "kbd-demo",
    registryDependencies: ["@coss/kbd"],
    type: "registry:example",
  },
  {
    categories: ["menu", "checkbox"],
    description: "Menu with checkbox items",
    files: [{ path: "examples/menu-checkbox.tsx", type: "registry:example" }],
    name: "menu-checkbox",
    registryDependencies: ["@coss/menu", "@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["menu"],
    description: "Close menu when items are clicked",
    files: [
      { path: "examples/menu-close-on-click.tsx", type: "registry:example" },
    ],
    name: "menu-close-on-click",
    registryDependencies: ["@coss/menu", "@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["menu"],
    description: "Basic menu",
    files: [{ path: "examples/menu-demo.tsx", type: "registry:example" }],
    name: "menu-demo",
    registryDependencies: ["@coss/menu", "@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["menu", "label"],
    description: "Menu items grouped with labels",
    files: [
      { path: "examples/menu-group-labels.tsx", type: "registry:example" },
    ],
    name: "menu-group-labels",
    registryDependencies: ["@coss/menu", "@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["menu"],
    description: "Open the menu on hover",
    files: [{ path: "examples/menu-hover.tsx", type: "registry:example" }],
    name: "menu-hover",
    registryDependencies: ["@coss/menu", "@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["menu", "link"],
    description: "Menu items as links",
    files: [{ path: "examples/menu-link.tsx", type: "registry:example" }],
    name: "menu-link",
    registryDependencies: ["@coss/menu", "@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["menu"],
    description: "Menu with submenu",
    files: [{ path: "examples/menu-nested.tsx", type: "registry:example" }],
    name: "menu-nested",
    registryDependencies: ["@coss/menu", "@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["menu", "radio"],
    description: "Menu with radio options",
    files: [
      { path: "examples/menu-radio-group.tsx", type: "registry:example" },
    ],
    name: "menu-radio-group",
    registryDependencies: ["@coss/menu", "@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["meter"],
    description: "Basic meter",
    files: [{ path: "examples/meter-demo.tsx", type: "registry:example" }],
    name: "meter-demo",
    registryDependencies: ["@coss/meter"],
    type: "registry:example",
  },
  {
    categories: ["meter"],
    description: "Meter without label and value",
    files: [{ path: "examples/meter-simple.tsx", type: "registry:example" }],
    name: "meter-simple",
    registryDependencies: ["@coss/meter"],
    type: "registry:example",
  },
  {
    categories: ["meter"],
    description: "Meter with a custom formatted value",
    files: [
      {
        path: "examples/meter-with-formatted-value.tsx",
        type: "registry:example",
      },
    ],
    name: "meter-with-formatted-value",
    registryDependencies: ["@coss/meter"],
    type: "registry:example",
  },
  {
    categories: ["meter"],
    description: "Meter with min and max values",
    files: [
      { path: "examples/meter-with-range.tsx", type: "registry:example" },
    ],
    name: "meter-with-range",
    registryDependencies: ["@coss/meter"],
    type: "registry:example",
  },
  {
    categories: ["number field"],
    description: "A number field",
    files: [
      { path: "examples/number-field-demo.tsx", type: "registry:example" },
    ],
    name: "number-field-demo",
    registryDependencies: ["@coss/number-field"],
    type: "registry:example",
  },
  {
    categories: ["number field"],
    description: "Small number field",
    files: [{ path: "examples/number-field-sm.tsx", type: "registry:example" }],
    name: "number-field-sm",
    registryDependencies: ["@coss/number-field"],
    type: "registry:example",
  },
  {
    categories: ["number field"],
    description: "Large number field",
    files: [{ path: "examples/number-field-lg.tsx", type: "registry:example" }],
    name: "number-field-lg",
    registryDependencies: ["@coss/number-field"],
    type: "registry:example",
  },
  {
    categories: ["number field", "disabled", "label"],
    description: "A disabled number field",
    files: [
      { path: "examples/number-field-disabled.tsx", type: "registry:example" },
    ],
    name: "number-field-disabled",
    registryDependencies: ["@coss/number-field"],
    type: "registry:example",
  },
  {
    categories: ["number field", "field", "form", "button"],
    description: "A number in a form",
    files: [
      { path: "examples/number-field-form.tsx", type: "registry:example" },
    ],
    name: "number-field-form",
    registryDependencies: [
      "@coss/number-field",
      "@coss/field",
      "@coss/form",
      "@coss/button",
    ],
    type: "registry:example",
  },
  {
    categories: ["number field"],
    description: "A number field with formatted value",
    files: [
      {
        path: "examples/number-field-with-formatted-value.tsx",
        type: "registry:example",
      },
    ],
    name: "number-field-with-formatted-value",
    registryDependencies: ["@coss/number-field"],
    type: "registry:example",
  },
  {
    categories: ["number field", "label"],
    description: "A number field with an external label",
    files: [
      {
        path: "examples/number-field-with-label.tsx",
        type: "registry:example",
      },
    ],
    name: "number-field-with-label",
    registryDependencies: ["@coss/number-field", "@coss/label"],
    type: "registry:example",
  },
  {
    categories: ["number field", "range"],
    description: "A number field with min/max constraints",
    files: [
      {
        path: "examples/number-field-with-range.tsx",
        type: "registry:example",
      },
    ],
    name: "number-field-with-range",
    registryDependencies: ["@coss/number-field"],
    type: "registry:example",
  },
  {
    categories: ["number field"],
    description: "A number field with a scrub area",
    files: [
      {
        path: "examples/number-field-with-scrub.tsx",
        type: "registry:example",
      },
    ],
    name: "number-field-with-scrub",
    registryDependencies: ["@coss/number-field"],
    type: "registry:example",
  },
  {
    categories: ["number field"],
    description: "A number field with step",
    files: [
      { path: "examples/number-field-with-step.tsx", type: "registry:example" },
    ],
    name: "number-field-with-step",
    registryDependencies: ["@coss/number-field"],
    type: "registry:example",
  },
  {
    categories: ["pagination"],
    description: "Pagination example",
    files: [{ path: "examples/pagination-demo.tsx", type: "registry:example" }],
    name: "pagination-demo",
    registryDependencies: ["@coss/pagination"],
    type: "registry:example",
  },
  {
    categories: ["popover", "button", "textarea", "form", "field"],
    description: "Popover with a form",
    files: [{ path: "examples/popover-demo.tsx", type: "registry:example" }],
    name: "popover-demo",
    registryDependencies: [
      "@coss/popover",
      "@coss/button",
      "@coss/textarea",
      "@coss/form",
      "@coss/field",
    ],
    type: "registry:example",
  },
  {
    categories: ["popover", "button"],
    description: "Popover with close button",
    files: [
      { path: "examples/popover-with-close.tsx", type: "registry:example" },
    ],
    name: "popover-with-close",
    registryDependencies: ["@coss/popover", "@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["preview card", "button"],
    description: "Preview card example",
    files: [
      { path: "examples/preview-card-demo.tsx", type: "registry:example" },
    ],
    name: "preview-card-demo",
    registryDependencies: ["@coss/preview-card", "@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["progress"],
    description: "Animated progress bar",
    files: [{ path: "examples/progress-demo.tsx", type: "registry:example" }],
    name: "progress-demo",
    registryDependencies: ["@coss/progress"],
    type: "registry:example",
  },
  {
    categories: ["progress"],
    description: "Progress with a custom formatted value",
    files: [
      {
        path: "examples/progress-with-formatted-value.tsx",
        type: "registry:example",
      },
    ],
    name: "progress-with-formatted-value",
    registryDependencies: ["@coss/progress"],
    type: "registry:example",
  },
  {
    categories: ["progress", "label"],
    description: "Progress with label and value",
    files: [
      {
        path: "examples/progress-with-label-value.tsx",
        type: "registry:example",
      },
    ],
    name: "progress-with-label-value",
    registryDependencies: ["@coss/progress"],
    type: "registry:example",
  },
  {
    categories: ["radio", "label"],
    description: "Card-style radio options",
    files: [
      { path: "examples/radio-group-card.tsx", type: "registry:example" },
    ],
    name: "radio-group-card",
    registryDependencies: ["@coss/radio-group", "@coss/label"],
    type: "registry:example",
  },
  {
    categories: ["radio", "label"],
    description: "Basic radio group",
    files: [
      { path: "examples/radio-group-demo.tsx", type: "registry:example" },
    ],
    name: "radio-group-demo",
    registryDependencies: ["@coss/radio-group", "@coss/label"],
    type: "registry:example",
  },
  {
    categories: ["radio", "label"],
    description: "Radio group with one option disabled",
    files: [
      { path: "examples/radio-group-disabled.tsx", type: "registry:example" },
    ],
    name: "radio-group-disabled",
    registryDependencies: ["@coss/radio-group", "@coss/label"],
    type: "registry:example",
  },
  {
    categories: ["radio", "field", "fieldset", "form", "button"],
    description: "Radio group in a form",
    files: [
      { path: "examples/radio-group-form.tsx", type: "registry:example" },
    ],
    name: "radio-group-form",
    registryDependencies: [
      "@coss/radio-group",
      "@coss/field",
      "@coss/fieldset",
      "@coss/form",
      "@coss/button",
    ],
    type: "registry:example",
  },
  {
    categories: ["radio", "label", "helper", "hint"],
    description: "Radio options with helper text",
    files: [
      {
        path: "examples/radio-group-with-description.tsx",
        type: "registry:example",
      },
    ],
    name: "radio-group-with-description",
    registryDependencies: ["@coss/radio-group", "@coss/label"],
    type: "registry:example",
  },
  {
    categories: ["scroll area"],
    description: "Scroll area - vertical",
    files: [
      {
        path: "examples/scroll-area-demo.tsx",
        type: "registry:example",
      },
    ],
    name: "scroll-area-demo",
    registryDependencies: ["@coss/scroll-area"],
    type: "registry:example",
  },
  {
    categories: ["scroll area"],
    description: "Scroll area - horizontal",
    files: [
      {
        path: "examples/scroll-area-horizontal.tsx",
        type: "registry:example",
      },
    ],
    name: "scroll-area-horizontal",
    registryDependencies: ["@coss/scroll-area"],
    type: "registry:example",
  },
  {
    categories: ["scroll area"],
    description: "Scroll area - both horizontal and vertical",
    files: [
      {
        path: "examples/scroll-area-both.tsx",
        type: "registry:example",
      },
    ],
    name: "scroll-area-both",
    registryDependencies: ["@coss/scroll-area"],
    type: "registry:example",
  },
  {
    categories: ["select"],
    description: "A basic select",
    files: [{ path: "examples/select-demo.tsx", type: "registry:example" }],
    name: "select-demo",
    registryDependencies: ["@coss/select"],
    type: "registry:example",
  },
  {
    categories: ["select"],
    description: "A select with small size",
    files: [{ path: "examples/select-sm.tsx", type: "registry:example" }],
    name: "select-sm",
    registryDependencies: ["@coss/select"],
    type: "registry:example",
  },
  {
    categories: ["select"],
    description: "A select with large size",
    files: [{ path: "examples/select-lg.tsx", type: "registry:example" }],
    name: "select-lg",
    registryDependencies: ["@coss/select"],
    type: "registry:example",
  },
  {
    categories: ["select", "disabled"],
    description: "A disabled select",
    files: [{ path: "examples/select-disabled.tsx", type: "registry:example" }],
    name: "select-disabled",
    registryDependencies: ["@coss/select"],
    type: "registry:example",
  },
  {
    categories: ["select"],
    description: "Select popup not aligned to trigger",
    files: [
      {
        path: "examples/select-without-alignment.tsx",
        type: "registry:example",
      },
    ],
    name: "select-without-alignment",
    registryDependencies: ["@coss/select"],
    type: "registry:example",
  },
  {
    categories: ["select"],
    description: "Select items grouped with labels",
    files: [
      { path: "examples/select-with-groups.tsx", type: "registry:example" },
    ],
    name: "select-with-groups",
    registryDependencies: ["@coss/select"],
    type: "registry:example",
  },
  {
    categories: ["select"],
    description: "Multiple selection with formatted value",
    files: [{ path: "examples/select-multiple.tsx", type: "registry:example" }],
    name: "select-multiple",
    registryDependencies: ["@coss/select"],
    type: "registry:example",
  },
  {
    categories: ["select"],
    description: "Select with icon",
    files: [
      { path: "examples/select-with-icon.tsx", type: "registry:example" },
    ],
    name: "select-with-icon",
    registryDependencies: ["@coss/select"],
    type: "registry:example",
  },
  {
    categories: ["select"],
    description: "Select options with icon",
    files: [
      {
        path: "examples/select-options-with-icon.tsx",
        type: "registry:example",
      },
    ],
    name: "select-options-with-icon",
    registryDependencies: ["@coss/select"],
    type: "registry:example",
  },
  {
    categories: ["select"],
    description: "Select with object values",
    files: [
      {
        path: "examples/select-with-object-values.tsx",
        type: "registry:example",
      },
    ],
    name: "select-with-object-values",
    registryDependencies: ["@coss/select"],
    type: "registry:example",
  },
  {
    categories: ["select", "form", "field", "helper", "hint"],
    description: "Select in a form",
    files: [{ path: "examples/select-form.tsx", type: "registry:example" }],
    name: "select-form",
    registryDependencies: [
      "@coss/button",
      "@coss/select",
      "@coss/form",
      "@coss/field",
    ],
    type: "registry:example",
  },
  {
    categories: ["separator"],
    description: "Separator with horizontal and vertical orientations",
    files: [{ path: "examples/separator-demo.tsx", type: "registry:example" }],
    name: "separator-demo",
    registryDependencies: ["@coss/separator"],
    type: "registry:example",
  },
  {
    categories: ["skeleton"],
    description: "Skeleton demo",
    files: [{ path: "examples/skeleton-demo.tsx", type: "registry:example" }],
    name: "skeleton-demo",
    registryDependencies: ["@coss/avatar", "@coss/button", "@coss/skeleton"],
    type: "registry:example",
  },
  {
    categories: ["skeleton"],
    description: "Skeleton only",
    files: [{ path: "examples/skeleton-only.tsx", type: "registry:example" }],
    name: "skeleton-only",
    registryDependencies: ["@coss/skeleton"],
    type: "registry:example",
  },
  {
    categories: ["slider"],
    description: "Basic slider",
    files: [{ path: "examples/slider-demo.tsx", type: "registry:example" }],
    name: "slider-demo",
    registryDependencies: ["@coss/slider"],
    type: "registry:example",
  },
  {
    categories: ["slider", "label"],
    description: "Slider with label and value",
    files: [
      {
        path: "examples/slider-with-label-value.tsx",
        type: "registry:example",
      },
    ],
    name: "slider-with-label-value",
    registryDependencies: ["@coss/slider", "@coss/label"],
    type: "registry:example",
  },
  {
    categories: ["slider", "range slider"],
    description: "Two-thumb range slider",
    files: [{ path: "examples/slider-range.tsx", type: "registry:example" }],
    name: "slider-range",
    registryDependencies: ["@coss/slider"],
    type: "registry:example",
  },
  {
    categories: ["slider", "vertical slider"],
    description: "Vertical slider",
    files: [{ path: "examples/slider-vertical.tsx", type: "registry:example" }],
    name: "slider-vertical",
    registryDependencies: ["@coss/slider"],
    type: "registry:example",
  },
  {
    categories: ["slider", "form", "field", "button", "helper", "hint"],
    description: "Slider in a form",
    files: [{ path: "examples/slider-form.tsx", type: "registry:example" }],
    name: "slider-form",
    registryDependencies: [
      "@coss/slider",
      "@coss/form",
      "@coss/field",
      "@coss/button",
    ],
    type: "registry:example",
  },
  {
    categories: ["spinner", "loading"],
    description: "Spinner demo",
    files: [{ path: "examples/spinner-demo.tsx", type: "registry:example" }],
    name: "spinner-demo",
    registryDependencies: ["@coss/spinner"],
    type: "registry:example",
  },
  {
    categories: ["switch", "label"],
    description: "Basic switch",
    files: [{ path: "examples/switch-demo.tsx", type: "registry:example" }],
    name: "switch-demo",
    registryDependencies: ["@coss/switch", "@coss/label"],
    type: "registry:example",
  },
  {
    categories: ["switch", "label", "disabled"],
    description: "Disabled switch",
    files: [{ path: "examples/switch-disabled.tsx", type: "registry:example" }],
    name: "switch-disabled",
    registryDependencies: ["@coss/switch", "@coss/label"],
    type: "registry:example",
  },
  {
    categories: ["switch", "label", "helper", "hint"],
    description: "Switch with description",
    files: [
      {
        path: "examples/switch-with-description.tsx",
        type: "registry:example",
      },
    ],
    name: "switch-with-description",
    registryDependencies: ["@coss/switch", "@coss/label"],
    type: "registry:example",
  },
  {
    categories: ["switch", "label", "card"],
    description: "Card-style switch",
    files: [{ path: "examples/switch-card.tsx", type: "registry:example" }],
    name: "switch-card",
    registryDependencies: ["@coss/switch", "@coss/label"],
    type: "registry:example",
  },
  {
    categories: ["switch", "form", "field", "button"],
    description: "Switch in a form",
    files: [{ path: "examples/switch-form.tsx", type: "registry:example" }],
    name: "switch-form",
    registryDependencies: [
      "@coss/switch",
      "@coss/field",
      "@coss/form",
      "@coss/button",
    ],
    type: "registry:example",
  },
  {
    categories: ["table", "badge"],
    description: "Basic table",
    files: [{ path: "examples/table-demo.tsx", type: "registry:example" }],
    name: "table-demo",
    registryDependencies: ["@coss/table", "@coss/badge"],
    type: "registry:example",
  },
  {
    categories: ["table", "badge", "frame"],
    description: "Framed table",
    files: [{ path: "examples/table-framed.tsx", type: "registry:example" }],
    name: "table-framed",
    registryDependencies: ["@coss/table", "@coss/badge", "@coss/frame"],
    type: "registry:example",
  },
  {
    categories: ["tabs"],
    description: "Tabs with default indicator",
    files: [{ path: "examples/tabs-demo.tsx", type: "registry:example" }],
    name: "tabs-demo",
    registryDependencies: ["@coss/tabs"],
    type: "registry:example",
  },
  {
    categories: ["tabs"],
    description: "Tabs with underline indicator",
    files: [{ path: "examples/tabs-underline.tsx", type: "registry:example" }],
    name: "tabs-underline",
    registryDependencies: ["@coss/tabs"],
    type: "registry:example",
  },
  {
    categories: ["tabs", "vertical tabs"],
    description: "Tabs with vertical layout",
    files: [{ path: "examples/tabs-vertical.tsx", type: "registry:example" }],
    name: "tabs-vertical",
    registryDependencies: ["@coss/tabs"],
    type: "registry:example",
  },
  {
    categories: ["tabs", "vertical tabs"],
    description: "Underline tabs with vertical layout",
    files: [
      {
        path: "examples/tabs-underline-vertical.tsx",
        type: "registry:example",
      },
    ],
    name: "tabs-underline-vertical",
    registryDependencies: ["@coss/tabs"],
    type: "registry:example",
  },
  {
    categories: ["textarea"],
    description: "Basic textarea",
    files: [{ path: "examples/textarea-demo.tsx", type: "registry:example" }],
    name: "textarea-demo",
    registryDependencies: ["@coss/textarea"],
    type: "registry:example",
  },
  {
    categories: ["textarea"],
    description: "Small textarea",
    files: [{ path: "examples/textarea-sm.tsx", type: "registry:example" }],
    name: "textarea-sm",
    registryDependencies: ["@coss/textarea"],
    type: "registry:example",
  },
  {
    categories: ["textarea"],
    description: "Large textarea",
    files: [{ path: "examples/textarea-lg.tsx", type: "registry:example" }],
    name: "textarea-lg",
    registryDependencies: ["@coss/textarea"],
    type: "registry:example",
  },
  {
    categories: ["textarea", "disabled"],
    description: "Disabled textarea",
    files: [
      { path: "examples/textarea-disabled.tsx", type: "registry:example" },
    ],
    name: "textarea-disabled",
    registryDependencies: ["@coss/textarea"],
    type: "registry:example",
  },
  {
    categories: ["textarea", "field", "label"],
    description: "Textarea labelled with Field",
    files: [
      { path: "examples/textarea-with-label.tsx", type: "registry:example" },
    ],
    name: "textarea-with-label",
    registryDependencies: ["@coss/textarea", "@coss/label"],
    type: "registry:example",
  },
  {
    categories: ["textarea", "form", "field", "button"],
    description: "Textarea in a form",
    files: [{ path: "examples/textarea-form.tsx", type: "registry:example" }],
    name: "textarea-form",
    registryDependencies: [
      "@coss/textarea",
      "@coss/form",
      "@coss/field",
      "@coss/button",
    ],
    type: "registry:example",
  },
  {
    categories: ["toast", "button"],
    description: "Status toast",
    files: [{ path: "examples/toast-demo.tsx", type: "registry:example" }],
    name: "toast-demo",
    registryDependencies: ["@coss/toast"],
    type: "registry:example",
  },
  {
    categories: ["toast", "button", "loading"],
    description: "Loading toast",
    files: [{ path: "examples/toast-loading.tsx", type: "registry:example" }],
    name: "toast-loading",
    registryDependencies: ["@coss/toast"],
    type: "registry:example",
  },
  {
    categories: ["toast", "button"],
    description: "Drive toasts from promise states",
    files: [{ path: "examples/toast-promise.tsx", type: "registry:example" }],
    name: "toast-promise",
    registryDependencies: ["@coss/toast"],
    type: "registry:example",
  },
  {
    categories: ["toast", "button"],
    description: "Toast with an action button",
    files: [
      { path: "examples/toast-with-action.tsx", type: "registry:example" },
    ],
    name: "toast-with-action",
    registryDependencies: ["@coss/toast"],
    type: "registry:example",
  },
  {
    categories: ["toast", "button"],
    description: "Success toast",
    files: [
      { path: "examples/toast-with-status.tsx", type: "registry:example" },
    ],
    name: "toast-with-status",
    registryDependencies: ["@coss/toast"],
    type: "registry:example",
  },
  {
    categories: ["toast"],
    description: "Toast with varying heights",
    files: [{ path: "examples/toast-heights.tsx", type: "registry:example" }],
    name: "toast-heights",
    registryDependencies: ["@coss/toast"],
    type: "registry:example",
  },
  {
    categories: ["toggle"],
    description: "Basic toggle",
    files: [{ path: "examples/toggle-demo.tsx", type: "registry:example" }],
    name: "toggle-demo",
    registryDependencies: ["@coss/toggle"],
    type: "registry:example",
  },
  {
    categories: ["toggle", "disabled"],
    description: "Disabled toggle",
    files: [{ path: "examples/toggle-disabled.tsx", type: "registry:example" }],
    name: "toggle-disabled",
    registryDependencies: ["@coss/toggle"],
    type: "registry:example",
  },
  {
    categories: ["toggle group", "toggle"],
    description: "Toggle group",
    files: [
      { path: "examples/toggle-group-demo.tsx", type: "registry:example" },
    ],
    name: "toggle-group-demo",
    registryDependencies: ["@coss/toggle-group"],
    type: "registry:example",
  },
  {
    categories: ["toggle group", "toggle"],
    description: "Toggle group with small toggles",
    files: [{ path: "examples/toggle-group-sm.tsx", type: "registry:example" }],
    name: "toggle-group-sm",
    registryDependencies: ["@coss/toggle-group"],
    type: "registry:example",
  },
  {
    categories: ["toggle group", "toggle"],
    description: "Toggle group with large toggles",
    files: [{ path: "examples/toggle-group-lg.tsx", type: "registry:example" }],
    name: "toggle-group-lg",
    registryDependencies: ["@coss/toggle-group"],
    type: "registry:example",
  },
  {
    categories: ["toggle group", "toggle"],
    description: "Toggle group with outline toggles",
    files: [
      { path: "examples/toggle-group-outline.tsx", type: "registry:example" },
    ],
    name: "toggle-group-outline",
    registryDependencies: ["@coss/toggle-group"],
    type: "registry:example",
  },
  {
    categories: ["toggle group", "toggle", "vertical"],
    description: "Toggle group with outline toggles and vertical layout",
    files: [
      {
        path: "examples/toggle-group-outline-vertical.tsx",
        type: "registry:example",
      },
    ],
    name: "toggle-group-outline-vertical",
    registryDependencies: ["@coss/toggle-group"],
    type: "registry:example",
  },
  {
    categories: ["toggle group", "toggle", "disabled"],
    description: "Disabled toggle group",
    files: [
      { path: "examples/toggle-group-disabled.tsx", type: "registry:example" },
    ],
    name: "toggle-group-disabled",
    registryDependencies: ["@coss/toggle-group"],
    type: "registry:example",
  },
  {
    categories: ["toggle group", "toggle"],
    description: "Toggle group with multiple selection",
    files: [
      { path: "examples/toggle-group-multiple.tsx", type: "registry:example" },
    ],
    name: "toggle-group-multiple",
    registryDependencies: ["@coss/toggle-group"],
    type: "registry:example",
  },
  {
    categories: ["toggle group", "toggle", "disabled"],
    description: "Toggle group with disabled item",
    files: [
      {
        path: "examples/toggle-group-with-disabled-item.tsx",
        type: "registry:example",
      },
    ],
    name: "toggle-group-with-disabled-item",
    registryDependencies: ["@coss/toggle-group"],
    type: "registry:example",
  },
  {
    categories: ["toggle"],
    description: "Multiple toggles",
    files: [
      { path: "examples/toggle-icon-group.tsx", type: "registry:example" },
    ],
    name: "toggle-icon-group",
    registryDependencies: ["@coss/toggle"],
    type: "registry:example",
  },
  {
    categories: ["toggle"],
    description: "Large toggle",
    files: [{ path: "examples/toggle-lg.tsx", type: "registry:example" }],
    name: "toggle-lg",
    registryDependencies: ["@coss/toggle"],
    type: "registry:example",
  },
  {
    categories: ["toggle"],
    description: "Outline toggle",
    files: [{ path: "examples/toggle-outline.tsx", type: "registry:example" }],
    name: "toggle-outline",
    registryDependencies: ["@coss/toggle"],
    type: "registry:example",
  },
  {
    categories: ["toggle"],
    description: "Small toggle",
    files: [{ path: "examples/toggle-sm.tsx", type: "registry:example" }],
    name: "toggle-sm",
    registryDependencies: ["@coss/toggle"],
    type: "registry:example",
  },
  {
    categories: ["toggle"],
    description: "Toggle with icon",
    files: [
      { path: "examples/toggle-with-icon.tsx", type: "registry:example" },
    ],
    name: "toggle-with-icon",
    registryDependencies: ["@coss/toggle"],
    type: "registry:example",
  },
  {
    categories: ["toolbar", "button", "select", "toggle", "tooltip"],
    description: "Toolbar",
    files: [{ path: "examples/toolbar-demo.tsx", type: "registry:example" }],
    name: "toolbar-demo",
    registryDependencies: [
      "@coss/button",
      "@coss/select",
      "@coss/toggle-group",
      "@coss/toolbar",
      "@coss/tooltip",
    ],
    type: "registry:example",
  },
  {
    categories: ["tooltip", "button"],
    description: "Basic tooltip",
    files: [{ path: "examples/tooltip-demo.tsx", type: "registry:example" }],
    name: "tooltip-demo",
    registryDependencies: ["@coss/tooltip", "@coss/button"],
    type: "registry:example",
  },
  {
    categories: ["tooltip", "toggle group", "toggle"],
    description: "Toggle group with grouped tooltips",
    files: [{ path: "examples/tooltip-grouped.tsx", type: "registry:example" }],
    name: "tooltip-grouped",
    registryDependencies: ["@coss/tooltip", "@coss/toggle-group"],
    type: "registry:example",
  },
];
