import type { Registry } from "shadcn/schema";

export const particles: Registry["items"] = [
  {
    categories: ["button"],
    description: "Back link button with chevron",
    files: [{ path: "particles/particle-bu-1.tsx", type: "registry:block" }],
    name: "particle-bu-1",
    registryDependencies: ["@coss/button"],
    type: "registry:block",
  },
  {
    categories: ["button"],
    description: "Card-style button with heading and description",
    files: [
      {
        path: "particles/particle-bu-2.tsx",
        type: "registry:block",
      },
    ],
    name: "particle-bu-2",
    registryDependencies: ["@coss/button"],
    type: "registry:block",
  },
  {
    categories: ["button"],
    description: "Directional pad control buttons",
    files: [{ path: "particles/particle-bu-3.tsx", type: "registry:block" }],
    name: "particle-bu-3",
    registryDependencies: ["@coss/button"],
    type: "registry:block",
  },
  {
    categories: ["button"],
    description: "Outline like button with count",
    files: [
      {
        path: "particles/particle-bu-4.tsx",
        type: "registry:block",
      },
    ],
    name: "particle-bu-4",
    registryDependencies: ["@coss/button"],
    type: "registry:block",
  },
  {
    categories: ["button"],
    dependencies: ["@remixicon/react"],
    description: "Social login icon buttons",
    files: [
      {
        path: "particles/particle-bu-5.tsx",
        type: "registry:block",
      },
    ],
    name: "particle-bu-5",
    registryDependencies: ["@coss/button"],
    type: "registry:block",
  },
  {
    categories: ["button"],
    description: "Expandable show more/less toggle button",
    files: [{ path: "particles/particle-bu-6.tsx", type: "registry:block" }],
    name: "particle-bu-6",
    registryDependencies: ["@coss/button"],
    type: "registry:block",
  },
  {
    categories: ["button"],
    description: "Star button with count badge",
    files: [{ path: "particles/particle-bu-7.tsx", type: "registry:block" }],
    name: "particle-bu-7",
    registryDependencies: ["@coss/button"],
    type: "registry:block",
  },
  {
    categories: ["frame", "collapsible"],
    description: "Frame with collapsible content and delete button",
    files: [{ path: "particles/particle-fr-1.tsx", type: "registry:block" }],
    name: "particle-fr-1",
    registryDependencies: ["@coss/frame", "@coss/collapsible", "@coss/button"],
    type: "registry:block",
  },
  {
    categories: ["input", "input group", "button", "popover"],
    description: "Input with start text and end tooltip",
    files: [{ path: "particles/particle-in-1.tsx", type: "registry:block" }],
    name: "particle-in-1",
    registryDependencies: [
      "@coss/button",
      "@coss/input-group",
      "@coss/popover",
    ],
    type: "registry:block",
  },
  {
    categories: ["input", "input group", "button", "tooltip"],
    description: "Password input with toggle visibility",
    files: [{ path: "particles/particle-in-2.tsx", type: "registry:block" }],
    name: "particle-in-2",
    registryDependencies: [
      "@coss/button",
      "@coss/input-group",
      "@coss/tooltip",
    ],
    type: "registry:block",
  },
  {
    categories: ["input", "input group", "button", "popover"],
    description: "Input group mimicking a URL bar",
    files: [{ path: "particles/particle-in-3.tsx", type: "registry:block" }],
    name: "particle-in-3",
    registryDependencies: [
      "@coss/button",
      "@coss/input-group",
      "@coss/popover",
    ],
    type: "registry:block",
  },
  {
    categories: ["input", "input group", "kbd", "search"],
    description: "Input group with keyboard shortcut",
    files: [{ path: "particles/particle-in-4.tsx", type: "registry:block" }],
    name: "particle-in-4",
    registryDependencies: ["@coss/input-group", "@coss/kbd"],
    type: "registry:block",
  },
  {
    categories: ["input", "input group", "loading", "spinner"],
    description: "Input group with start loading spinner",
    files: [{ path: "particles/particle-in-5.tsx", type: "registry:block" }],
    name: "particle-in-5",
    registryDependencies: ["@coss/input-group", "@coss/spinner"],
    type: "registry:block",
  },
  {
    categories: ["pagination"],
    description: "Pagination with previous and next buttons only",
    files: [{ path: "particles/particle-pa-1.tsx", type: "registry:block" }],
    name: "particle-pa-1",
    registryDependencies: ["@coss/pagination"],
    type: "registry:block",
  },
  {
    categories: ["pagination", "select"],
    description: "Pagination with select, and previous and next buttons",
    files: [{ path: "particles/particle-pa-2.tsx", type: "registry:block" }],
    name: "particle-pa-2",
    registryDependencies: ["@coss/pagination", "@coss/select"],
    type: "registry:block",
  },
];
