import type { Registry } from "shadcn/schema";

import type { RegistryCategory } from "./registry-categories";

// Type helper to enforce RegistryCategory[] for categories field
type ParticleItem = Omit<Registry["items"][number], "categories"> & {
  categories?: RegistryCategory[];
};

// Helper function to ensure categories are valid RegistryCategory values
function categories<T extends RegistryCategory[]>(...categories: T): T {
  return categories;
}

export const particles: ParticleItem[] = [
  {
    categories: categories("accordion"),
    description: "Basic accordion",
    files: [{ path: "particles/particle-ac-1.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full sm:**:data-[slot=preview]:max-w-[80%]",
    },
    name: "particle-ac-1",
    registryDependencies: ["@coss/accordion"],
    type: "registry:block",
  },
  {
    categories: categories("accordion"),
    description: "Accordion with one panel open",
    files: [{ path: "particles/particle-ac-2.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full sm:**:data-[slot=preview]:max-w-[80%]",
    },
    name: "particle-ac-2",
    registryDependencies: ["@coss/accordion"],
    type: "registry:block",
  },
  {
    categories: categories("accordion"),
    description: "Accordion allowing multiple panels open",
    files: [{ path: "particles/particle-ac-3.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full sm:**:data-[slot=preview]:max-w-[80%]",
    },
    name: "particle-ac-3",
    registryDependencies: ["@coss/accordion"],
    type: "registry:block",
  },
  {
    categories: categories("accordion"),
    description: "Controlled accordion",
    files: [{ path: "particles/particle-ac-4.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full sm:**:data-[slot=preview]:max-w-[80%]",
    },
    name: "particle-ac-4",
    registryDependencies: ["@coss/accordion", "@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("alert"),
    description: "Basic alert",
    files: [{ path: "particles/particle-al-1.tsx", type: "registry:block" }],
    meta: {
      className: "**:data-[slot=preview]:w-full",
    },
    name: "particle-al-1",
    registryDependencies: ["@coss/alert"],
    type: "registry:block",
  },
  {
    categories: categories("alert"),
    dependencies: ["lucide-react"],
    description: "Alert with icon",
    files: [{ path: "particles/particle-al-2.tsx", type: "registry:block" }],
    meta: {
      className: "**:data-[slot=preview]:w-full",
    },
    name: "particle-al-2",
    registryDependencies: ["@coss/alert"],
    type: "registry:block",
  },
  {
    categories: categories("alert"),
    dependencies: ["lucide-react"],
    description: "Alert with icon and action buttons",
    files: [{ path: "particles/particle-al-3.tsx", type: "registry:block" }],
    meta: {
      className: "**:data-[slot=preview]:w-full",
    },
    name: "particle-al-3",
    registryDependencies: ["@coss/alert", "@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("alert", "info"),
    dependencies: ["lucide-react"],
    description: "Info alert",
    files: [{ path: "particles/particle-al-4.tsx", type: "registry:block" }],
    meta: {
      className: "**:data-[slot=preview]:w-full",
    },
    name: "particle-al-4",
    registryDependencies: ["@coss/alert"],
    type: "registry:block",
  },
  {
    categories: categories("alert", "success"),
    dependencies: ["lucide-react"],
    description: "Success alert",
    files: [{ path: "particles/particle-al-5.tsx", type: "registry:block" }],
    meta: {
      className: "**:data-[slot=preview]:w-full",
    },
    name: "particle-al-5",
    registryDependencies: ["@coss/alert"],
    type: "registry:block",
  },
  {
    categories: categories("alert", "warning"),
    dependencies: ["lucide-react"],
    description: "Warning alert",
    files: [{ path: "particles/particle-al-6.tsx", type: "registry:block" }],
    meta: {
      className: "**:data-[slot=preview]:w-full",
    },
    name: "particle-al-6",
    registryDependencies: ["@coss/alert"],
    type: "registry:block",
  },
  {
    categories: categories("alert", "error"),
    dependencies: ["lucide-react"],
    description: "Error alert",
    files: [{ path: "particles/particle-al-7.tsx", type: "registry:block" }],
    meta: {
      className: "**:data-[slot=preview]:w-full",
    },
    name: "particle-al-7",
    registryDependencies: ["@coss/alert"],
    type: "registry:block",
  },
  {
    categories: categories("alert dialog", "dialog"),
    description: "Alert dialog",
    files: [{ path: "particles/particle-ad-1.tsx", type: "registry:block" }],
    name: "particle-ad-1",
    registryDependencies: ["@coss/alert-dialog", "@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("autocomplete", "input"),
    description: "Basic autocomplete",
    files: [{ path: "particles/particle-au-1.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-au-1",
    registryDependencies: ["@coss/autocomplete"],
    type: "registry:block",
  },
  {
    categories: categories("autocomplete", "input", "disabled"),
    description: "Disabled autocomplete",
    files: [{ path: "particles/particle-au-2.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-au-2",
    registryDependencies: ["@coss/autocomplete"],
    type: "registry:block",
  },
  {
    categories: categories("autocomplete", "input"),
    description: "Small autocomplete",
    files: [{ path: "particles/particle-au-3.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-au-3",
    registryDependencies: ["@coss/autocomplete"],
    type: "registry:block",
  },
  {
    categories: categories("autocomplete", "input"),
    description: "Large autocomplete",
    files: [{ path: "particles/particle-au-4.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-au-4",
    registryDependencies: ["@coss/autocomplete"],
    type: "registry:block",
  },
  {
    categories: categories("autocomplete", "input"),
    description: "Autocomplete with label",
    files: [{ path: "particles/particle-au-5.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-au-5",
    registryDependencies: ["@coss/autocomplete", "@coss/label"],
    type: "registry:block",
  },
  {
    categories: categories("autocomplete", "input"),
    description: "Autocomplete autofilling the input with the highlighted item",
    files: [{ path: "particles/particle-au-6.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-au-6",
    registryDependencies: ["@coss/autocomplete"],
    type: "registry:block",
  },
  {
    categories: categories("autocomplete", "input"),
    description: "Autocomplete auto highlighting the first option",
    files: [{ path: "particles/particle-au-7.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-au-7",
    registryDependencies: ["@coss/autocomplete"],
    type: "registry:block",
  },
  {
    categories: categories("autocomplete", "input"),
    description: "Autocomplete with clear button",
    files: [{ path: "particles/particle-au-8.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-au-8",
    registryDependencies: ["@coss/autocomplete"],
    type: "registry:block",
  },
  {
    categories: categories("autocomplete", "input"),
    description: "Autocomplete with trigger and clear buttons",
    files: [{ path: "particles/particle-au-9.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-au-9",
    registryDependencies: ["@coss/autocomplete"],
    type: "registry:block",
  },
  {
    categories: categories("autocomplete", "input"),
    description: "Autocomplete with grouped items",
    files: [{ path: "particles/particle-au-10.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-au-10",
    registryDependencies: ["@coss/autocomplete"],
    type: "registry:block",
  },
  {
    categories: categories("autocomplete", "input"),
    description: "Autocomplete with limited number of results",
    files: [{ path: "particles/particle-au-11.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-au-11",
    registryDependencies: ["@coss/autocomplete"],
    type: "registry:block",
  },
  {
    categories: categories("autocomplete", "input", "async"),
    description: "Autocomplete with async items loading",
    files: [{ path: "particles/particle-au-12.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-au-12",
    registryDependencies: ["@coss/autocomplete", "@coss/spinner"],
    type: "registry:block",
  },
  {
    categories: categories("autocomplete", "input", "form"),
    description: "Autocomplete form",
    files: [{ path: "particles/particle-au-13.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-au-13",
    registryDependencies: ["@coss/autocomplete", "@coss/form", "@coss/field"],
    type: "registry:block",
  },
  {
    categories: categories("avatar"),
    description: "Avatar with image and fallback",
    files: [{ path: "particles/particle-av-1.tsx", type: "registry:block" }],
    name: "particle-av-1",
    registryDependencies: ["@coss/avatar"],
    type: "registry:block",
  },
  {
    categories: categories("avatar"),
    description: "Fallback-only avatar",
    files: [{ path: "particles/particle-av-2.tsx", type: "registry:block" }],
    name: "particle-av-2",
    registryDependencies: ["@coss/avatar"],
    type: "registry:block",
  },
  {
    categories: categories("avatar"),
    description: "Avatars with different sizes",
    files: [{ path: "particles/particle-av-3.tsx", type: "registry:block" }],
    name: "particle-av-3",
    registryDependencies: ["@coss/avatar"],
    type: "registry:block",
  },
  {
    categories: categories("avatar"),
    description: "Avatars with different radii",
    files: [{ path: "particles/particle-av-4.tsx", type: "registry:block" }],
    name: "particle-av-4",
    registryDependencies: ["@coss/avatar"],
    type: "registry:block",
  },
  {
    categories: categories("avatar"),
    description: "Overlapping avatar group",
    files: [{ path: "particles/particle-av-5.tsx", type: "registry:block" }],
    name: "particle-av-5",
    registryDependencies: ["@coss/avatar"],
    type: "registry:block",
  },
  {
    categories: categories("badge"),
    description: "Basic badge",
    files: [{ path: "particles/particle-bg-1.tsx", type: "registry:block" }],
    name: "particle-bg-1",
    registryDependencies: ["@coss/badge"],
    type: "registry:block",
  },
  {
    categories: categories("badge"),
    description: "Outline badge",
    files: [{ path: "particles/particle-bg-2.tsx", type: "registry:block" }],
    name: "particle-bg-2",
    registryDependencies: ["@coss/badge"],
    type: "registry:block",
  },
  {
    categories: categories("badge"),
    description: "Secondary badge",
    files: [{ path: "particles/particle-bg-3.tsx", type: "registry:block" }],
    name: "particle-bg-3",
    registryDependencies: ["@coss/badge"],
    type: "registry:block",
  },
  {
    categories: categories("badge", "error"),
    description: "Destructive badge",
    files: [{ path: "particles/particle-bg-4.tsx", type: "registry:block" }],
    name: "particle-bg-4",
    registryDependencies: ["@coss/badge"],
    type: "registry:block",
  },
  {
    categories: categories("badge", "info"),
    description: "Info badge",
    files: [{ path: "particles/particle-bg-5.tsx", type: "registry:block" }],
    name: "particle-bg-5",
    registryDependencies: ["@coss/badge"],
    type: "registry:block",
  },
  {
    categories: categories("badge", "success"),
    description: "Success badge",
    files: [{ path: "particles/particle-bg-6.tsx", type: "registry:block" }],
    name: "particle-bg-6",
    registryDependencies: ["@coss/badge"],
    type: "registry:block",
  },
  {
    categories: categories("badge", "warning"),
    description: "Warning badge",
    files: [{ path: "particles/particle-bg-7.tsx", type: "registry:block" }],
    name: "particle-bg-7",
    registryDependencies: ["@coss/badge"],
    type: "registry:block",
  },
  {
    categories: categories("badge", "error"),
    description: "Error badge",
    files: [{ path: "particles/particle-bg-8.tsx", type: "registry:block" }],
    name: "particle-bg-8",
    registryDependencies: ["@coss/badge"],
    type: "registry:block",
  },
  {
    categories: categories("badge"),
    description: "Small badge",
    files: [{ path: "particles/particle-bg-9.tsx", type: "registry:block" }],
    name: "particle-bg-9",
    registryDependencies: ["@coss/badge"],
    type: "registry:block",
  },
  {
    categories: categories("badge"),
    description: "Large badge",
    files: [{ path: "particles/particle-bg-10.tsx", type: "registry:block" }],
    name: "particle-bg-10",
    registryDependencies: ["@coss/badge"],
    type: "registry:block",
  },
  {
    categories: categories("badge"),
    dependencies: ["lucide-react"],
    description: "Badge with icon",
    files: [{ path: "particles/particle-bg-11.tsx", type: "registry:block" }],
    name: "particle-bg-11",
    registryDependencies: ["@coss/badge"],
    type: "registry:block",
  },
  {
    categories: categories("badge"),
    description: "Badge with link",
    files: [{ path: "particles/particle-bg-12.tsx", type: "registry:block" }],
    name: "particle-bg-12",
    registryDependencies: ["@coss/badge"],
    type: "registry:block",
  },
  {
    categories: categories("breadcrumb", "menu"),
    description: "Breadcrumb with menu example",
    files: [{ path: "particles/particle-bc-1.tsx", type: "registry:block" }],
    name: "particle-bc-1",
    registryDependencies: ["@coss/breadcrumb", "@coss/menu"],
    type: "registry:block",
  },
  {
    categories: categories("breadcrumb"),
    description: "Breadcrumb with custom separator",
    files: [{ path: "particles/particle-bc-2.tsx", type: "registry:block" }],
    name: "particle-bc-2",
    registryDependencies: ["@coss/breadcrumb"],
    type: "registry:block",
  },
  {
    categories: categories("button"),
    description: "Default button",
    files: [{ path: "particles/particle-bt-1.tsx", type: "registry:block" }],
    name: "particle-bt-1",
    registryDependencies: ["@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("button"),
    description: "Outline button",
    files: [{ path: "particles/particle-bt-2.tsx", type: "registry:block" }],
    name: "particle-bt-2",
    registryDependencies: ["@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("button"),
    description: "Secondary button",
    files: [{ path: "particles/particle-bt-3.tsx", type: "registry:block" }],
    name: "particle-bt-3",
    registryDependencies: ["@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("button"),
    description: "Destructive button",
    files: [{ path: "particles/particle-bt-4.tsx", type: "registry:block" }],
    name: "particle-bt-4",
    registryDependencies: ["@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("button"),
    description: "Destructive outline button",
    files: [{ path: "particles/particle-bt-5.tsx", type: "registry:block" }],
    name: "particle-bt-5",
    registryDependencies: ["@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("button"),
    description: "Ghost button",
    files: [{ path: "particles/particle-bt-6.tsx", type: "registry:block" }],
    name: "particle-bt-6",
    registryDependencies: ["@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("button"),
    description: "Link button",
    files: [{ path: "particles/particle-bt-7.tsx", type: "registry:block" }],
    name: "particle-bt-7",
    registryDependencies: ["@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("button"),
    description: "Extra-small button",
    files: [{ path: "particles/particle-bt-8.tsx", type: "registry:block" }],
    name: "particle-bt-8",
    registryDependencies: ["@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("button"),
    description: "Small button",
    files: [{ path: "particles/particle-bt-9.tsx", type: "registry:block" }],
    name: "particle-bt-9",
    registryDependencies: ["@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("button"),
    description: "Large button",
    files: [{ path: "particles/particle-bt-10.tsx", type: "registry:block" }],
    name: "particle-bt-10",
    registryDependencies: ["@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("button"),
    description: "Extra-large button",
    files: [{ path: "particles/particle-bt-11.tsx", type: "registry:block" }],
    name: "particle-bt-11",
    registryDependencies: ["@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("button", "disabled"),
    description: "Disabled button",
    files: [{ path: "particles/particle-bt-12.tsx", type: "registry:block" }],
    name: "particle-bt-12",
    registryDependencies: ["@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("button"),
    dependencies: ["lucide-react"],
    description: "Icon button",
    files: [{ path: "particles/particle-bt-13.tsx", type: "registry:block" }],
    name: "particle-bt-13",
    registryDependencies: ["@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("button"),
    dependencies: ["lucide-react"],
    description: "Small icon button",
    files: [{ path: "particles/particle-bt-14.tsx", type: "registry:block" }],
    name: "particle-bt-14",
    registryDependencies: ["@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("button"),
    dependencies: ["lucide-react"],
    description: "Large icon button",
    files: [{ path: "particles/particle-bt-15.tsx", type: "registry:block" }],
    name: "particle-bt-15",
    registryDependencies: ["@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("button"),
    dependencies: ["lucide-react"],
    description: "Button with icon",
    files: [{ path: "particles/particle-bt-16.tsx", type: "registry:block" }],
    name: "particle-bt-16",
    registryDependencies: ["@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("button"),
    description: "Link rendered as button",
    files: [{ path: "particles/particle-bt-17.tsx", type: "registry:block" }],
    name: "particle-bt-17",
    registryDependencies: ["@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("button", "loading"),
    description: "Loading button",
    files: [{ path: "particles/particle-bt-18.tsx", type: "registry:block" }],
    name: "particle-bt-18",
    registryDependencies: ["@coss/button", "@coss/spinner"],
    type: "registry:block",
  },
  {
    categories: categories("button"),
    dependencies: ["lucide-react"],
    description: "Back link button with chevron",
    files: [{ path: "particles/particle-bt-20.tsx", type: "registry:block" }],
    name: "particle-bt-20",
    registryDependencies: ["@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("button"),
    dependencies: ["lucide-react"],
    description: "Card-style button with heading and description",
    files: [
      {
        path: "particles/particle-bt-21.tsx",
        type: "registry:block",
      },
    ],
    name: "particle-bt-21",
    registryDependencies: ["@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("button"),
    dependencies: ["lucide-react"],
    description: "Directional pad control buttons",
    files: [{ path: "particles/particle-bt-22.tsx", type: "registry:block" }],
    name: "particle-bt-22",
    registryDependencies: ["@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("button"),
    dependencies: ["lucide-react"],
    description: "Outline like button with count",
    files: [
      {
        path: "particles/particle-bt-23.tsx",
        type: "registry:block",
      },
    ],
    name: "particle-bt-23",
    registryDependencies: ["@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("button"),
    dependencies: ["@remixicon/react"],
    description: "Social login icon buttons",
    files: [
      {
        path: "particles/particle-bt-24.tsx",
        type: "registry:block",
      },
    ],
    name: "particle-bt-24",
    registryDependencies: ["@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("button"),
    dependencies: ["lucide-react"],
    description: "Expandable show more/less toggle button",
    files: [{ path: "particles/particle-bt-25.tsx", type: "registry:block" }],
    name: "particle-bt-25",
    registryDependencies: ["@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("button"),
    dependencies: ["lucide-react"],
    description: "Star button with count badge",
    files: [{ path: "particles/particle-bt-26.tsx", type: "registry:block" }],
    name: "particle-bt-26",
    registryDependencies: ["@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("card"),
    description: "Card with header, content, and footer",
    files: [{ path: "particles/particle-cd-1.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:flex **:data-[slot=preview]:justify-center",
    },
    name: "particle-cd-1",
    registryDependencies: [
      "@coss/card",
      "@coss/button",
      "@coss/form",
      "@coss/field",
      "@coss/input",
      "@coss/select",
    ],
    type: "registry:block",
  },
  {
    categories: categories("checkbox"),
    description: "Basic checkbox",
    files: [{ path: "particles/particle-cb-1.tsx", type: "registry:block" }],
    name: "particle-cb-1",
    registryDependencies: ["@coss/checkbox", "@coss/label"],
    type: "registry:block",
  },
  {
    categories: categories("checkbox", "disabled"),
    description: "Disabled checkbox",
    files: [{ path: "particles/particle-cb-2.tsx", type: "registry:block" }],
    name: "particle-cb-2",
    registryDependencies: ["@coss/checkbox", "@coss/label"],
    type: "registry:block",
  },
  {
    categories: categories("checkbox"),
    description: "Checkbox with description",
    files: [{ path: "particles/particle-cb-3.tsx", type: "registry:block" }],
    name: "particle-cb-3",
    registryDependencies: ["@coss/checkbox", "@coss/label"],
    type: "registry:block",
  },
  {
    categories: categories("checkbox"),
    description: "Card-style checkbox",
    files: [{ path: "particles/particle-cb-4.tsx", type: "registry:block" }],
    name: "particle-cb-4",
    registryDependencies: ["@coss/checkbox", "@coss/label"],
    type: "registry:block",
  },
  {
    categories: categories("checkbox", "form"),
    description: "Checkbox form",
    files: [{ path: "particles/particle-cb-5.tsx", type: "registry:block" }],
    name: "particle-cb-5",
    registryDependencies: [
      "@coss/checkbox",
      "@coss/form",
      "@coss/field",
      "@coss/button",
    ],
    type: "registry:block",
  },
  {
    categories: categories("checkbox", "checkbox group"),
    description: "Basic checkbox group",
    files: [{ path: "particles/particle-cg-1.tsx", type: "registry:block" }],
    name: "particle-cg-1",
    registryDependencies: [
      "@coss/checkbox-group",
      "@coss/checkbox",
      "@coss/label",
    ],
    type: "registry:block",
  },
  {
    categories: categories("checkbox", "checkbox group", "disabled"),
    description: "Checkbox group with disabled items",
    files: [{ path: "particles/particle-cg-2.tsx", type: "registry:block" }],
    name: "particle-cg-2",
    registryDependencies: [
      "@coss/checkbox-group",
      "@coss/checkbox",
      "@coss/label",
    ],
    type: "registry:block",
  },
  {
    categories: categories("checkbox", "checkbox group"),
    description: "Checkbox group with parent checkbox",
    files: [{ path: "particles/particle-cg-3.tsx", type: "registry:block" }],
    name: "particle-cg-3",
    registryDependencies: [
      "@coss/checkbox-group",
      "@coss/checkbox",
      "@coss/label",
    ],
    type: "registry:block",
  },
  {
    categories: categories("checkbox", "checkbox group"),
    description: "Nested checkbox group with parent",
    files: [{ path: "particles/particle-cg-4.tsx", type: "registry:block" }],
    name: "particle-cg-4",
    registryDependencies: [
      "@coss/checkbox-group",
      "@coss/checkbox",
      "@coss/label",
    ],
    type: "registry:block",
  },
  {
    categories: categories("checkbox", "checkbox group", "form"),
    description: "Checkbox group form",
    files: [{ path: "particles/particle-cg-5.tsx", type: "registry:block" }],
    name: "particle-cg-5",
    registryDependencies: [
      "@coss/checkbox-group",
      "@coss/checkbox",
      "@coss/form",
      "@coss/field",
      "@coss/fieldset",
      "@coss/button",
    ],
    type: "registry:block",
  },
  {
    categories: categories("collapsible"),
    dependencies: ["lucide-react"],
    description: "Basic collapsible",
    files: [{ path: "particles/particle-cl-1.tsx", type: "registry:block" }],
    name: "particle-cl-1",
    registryDependencies: ["@coss/collapsible"],
    type: "registry:block",
  },
  {
    categories: categories("combobox", "input"),
    description: "Basic combobox",
    files: [{ path: "particles/particle-cx-1.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-cx-1",
    registryDependencies: ["@coss/combobox"],
    type: "registry:block",
  },
  {
    categories: categories("combobox", "input", "disabled"),
    description: "Disabled combobox",
    files: [{ path: "particles/particle-cx-2.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-cx-2",
    registryDependencies: ["@coss/combobox"],
    type: "registry:block",
  },
  {
    categories: categories("combobox", "input"),
    description: "Small combobox",
    files: [{ path: "particles/particle-cx-3.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-cx-3",
    registryDependencies: ["@coss/combobox"],
    type: "registry:block",
  },
  {
    categories: categories("combobox", "input"),
    description: "Large combobox",
    files: [{ path: "particles/particle-cx-4.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-cx-4",
    registryDependencies: ["@coss/combobox"],
    type: "registry:block",
  },
  {
    categories: categories("combobox", "input"),
    description: "Combobox with label",
    files: [{ path: "particles/particle-cx-5.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-cx-5",
    registryDependencies: ["@coss/combobox", "@coss/label"],
    type: "registry:block",
  },
  {
    categories: categories("combobox", "input"),
    description: "Combobox auto highlighting the first option",
    files: [{ path: "particles/particle-cx-6.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-cx-6",
    registryDependencies: ["@coss/combobox"],
    type: "registry:block",
  },
  {
    categories: categories("combobox", "input"),
    description: "Combobox with clear button",
    files: [{ path: "particles/particle-cx-7.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-cx-7",
    registryDependencies: ["@coss/combobox"],
    type: "registry:block",
  },
  {
    categories: categories("combobox", "input"),
    description: "Combobox with grouped items",
    files: [{ path: "particles/particle-cx-8.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-cx-8",
    registryDependencies: ["@coss/combobox"],
    type: "registry:block",
  },
  {
    categories: categories("combobox", "input"),
    description: "Combobox with multiple selection",
    files: [{ path: "particles/particle-cx-9.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-cx-9",
    registryDependencies: ["@coss/combobox"],
    type: "registry:block",
  },
  {
    categories: categories("combobox", "input"),
    dependencies: ["lucide-react"],
    description: "Combobox with input inside popup",
    files: [{ path: "particles/particle-cx-10.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-cx-10",
    registryDependencies: ["@coss/combobox", "@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("combobox", "input", "form"),
    description: "Combobox form",
    files: [{ path: "particles/particle-cx-11.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-cx-11",
    registryDependencies: [
      "@coss/combobox",
      "@coss/form",
      "@coss/field",
      "@coss/button",
    ],
    type: "registry:block",
  },
  {
    categories: categories("combobox", "input", "form"),
    description: "Combobox multiple form",
    files: [{ path: "particles/particle-cx-12.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-cx-12",
    registryDependencies: [
      "@coss/combobox",
      "@coss/form",
      "@coss/field",
      "@coss/button",
    ],
    type: "registry:block",
  },
  {
    categories: categories("dialog"),
    description: "Dialog with form",
    files: [{ path: "particles/particle-dg-1.tsx", type: "registry:block" }],
    name: "particle-dg-1",
    registryDependencies: [
      "@coss/dialog",
      "@coss/button",
      "@coss/form",
      "@coss/field",
      "@coss/input",
    ],
    type: "registry:block",
  },
  {
    categories: categories("dialog", "menu"),
    description: "Dialog opened from menu",
    files: [{ path: "particles/particle-dg-2.tsx", type: "registry:block" }],
    name: "particle-dg-2",
    registryDependencies: ["@coss/dialog", "@coss/menu", "@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("dialog"),
    description: "Nested dialogs",
    files: [{ path: "particles/particle-dg-3.tsx", type: "registry:block" }],
    name: "particle-dg-3",
    registryDependencies: [
      "@coss/dialog",
      "@coss/button",
      "@coss/field",
      "@coss/input",
    ],
    type: "registry:block",
  },
  {
    categories: categories("dialog", "alert dialog"),
    description: "Dialog with close confirmation",
    files: [{ path: "particles/particle-dg-4.tsx", type: "registry:block" }],
    name: "particle-dg-4",
    registryDependencies: [
      "@coss/dialog",
      "@coss/alert-dialog",
      "@coss/button",
      "@coss/form",
      "@coss/field",
      "@coss/textarea",
    ],
    type: "registry:block",
  },
  {
    categories: categories("empty state"),
    dependencies: ["lucide-react"],
    description: "Empty state with icon and actions",
    files: [{ path: "particles/particle-em-1.tsx", type: "registry:block" }],
    name: "particle-em-1",
    registryDependencies: ["@coss/empty", "@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("field", "label"),
    description: "Field with description",
    files: [{ path: "particles/particle-fd-1.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-fd-1",
    registryDependencies: ["@coss/field", "@coss/input"],
    type: "registry:block",
  },
  {
    categories: categories("field", "label"),
    description: "Field with required indicator",
    files: [{ path: "particles/particle-fd-2.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-fd-2",
    registryDependencies: ["@coss/field", "@coss/input"],
    type: "registry:block",
  },
  {
    categories: categories("field", "label", "disabled"),
    description: "Field in disabled state",
    files: [{ path: "particles/particle-fd-3.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-fd-3",
    registryDependencies: ["@coss/field", "@coss/input"],
    type: "registry:block",
  },
  {
    categories: categories("field", "label", "error"),
    description: "Field showing validation error",
    files: [{ path: "particles/particle-fd-4.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-fd-4",
    registryDependencies: ["@coss/field", "@coss/input"],
    type: "registry:block",
  },
  {
    categories: categories("field"),
    description: "Show field validity state",
    files: [{ path: "particles/particle-fd-5.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-fd-5",
    registryDependencies: ["@coss/field", "@coss/input"],
    type: "registry:block",
  },
  {
    categories: categories("input", "input group", "field", "button"),
    description: "Input group with field",
    files: [{ path: "particles/particle-fd-6.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-fd-6",
    registryDependencies: ["@coss/field", "@coss/button", "@coss/input-group"],
    type: "registry:block",
  },
  {
    categories: categories("field", "input", "autocomplete", "label"),
    description: "Field with autocomplete",
    files: [{ path: "particles/particle-fd-7.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-fd-7",
    registryDependencies: ["@coss/field", "@coss/autocomplete"],
    type: "registry:block",
  },
  {
    categories: categories("field", "input", "combobox", "label"),
    description: "Field with combobox",
    files: [{ path: "particles/particle-fd-8.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-fd-8",
    registryDependencies: ["@coss/field", "@coss/combobox"],
    type: "registry:block",
  },
  {
    categories: categories("field", "input", "combobox", "label"),
    description: "Field with multiple selection combobox",
    files: [{ path: "particles/particle-fd-9.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-fd-9",
    registryDependencies: ["@coss/field", "@coss/combobox"],
    type: "registry:block",
  },
  {
    categories: categories("field", "textarea", "label"),
    description: "Field with textarea",
    files: [{ path: "particles/particle-fd-10.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-fd-10",
    registryDependencies: ["@coss/field", "@coss/textarea"],
    type: "registry:block",
  },
  {
    categories: categories("field", "select", "label"),
    description: "Field with select",
    files: [{ path: "particles/particle-fd-11.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-fd-11",
    registryDependencies: ["@coss/field", "@coss/select"],
    type: "registry:block",
  },
  {
    categories: categories("field", "label", "checkbox"),
    description: "Field with checkbox",
    files: [{ path: "particles/particle-fd-12.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-fd-12",
    registryDependencies: ["@coss/field", "@coss/checkbox"],
    type: "registry:block",
  },
  {
    categories: categories(
      "field",
      "checkbox group",
      "checkbox",
      "fieldset",
      "label",
    ),
    description: "Field with checkbox group",
    files: [{ path: "particles/particle-fd-13.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-fd-13",
    registryDependencies: [
      "@coss/field",
      "@coss/checkbox-group",
      "@coss/checkbox",
      "@coss/fieldset",
    ],
    type: "registry:block",
  },
  {
    categories: categories("field", "radio group", "label", "fieldset"),
    description: "Field with radio group",
    files: [{ path: "particles/particle-fd-14.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-fd-14",
    registryDependencies: [
      "@coss/field",
      "@coss/radio-group",
      "@coss/fieldset",
    ],
    type: "registry:block",
  },
  {
    categories: categories("field", "switch", "label"),
    description: "Field with toggle switch",
    files: [{ path: "particles/particle-fd-15.tsx", type: "registry:block" }],
    name: "particle-fd-15",
    registryDependencies: ["@coss/field", "@coss/switch"],
    type: "registry:block",
  },
  {
    categories: categories("field", "slider", "label"),
    description: "Field with slider",
    files: [{ path: "particles/particle-fd-16.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-fd-16",
    registryDependencies: ["@coss/field", "@coss/slider"],
    type: "registry:block",
  },
  {
    categories: categories("field", "input", "label", "number field"),
    description: "Field with number field",
    files: [{ path: "particles/particle-fd-17.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-fd-17",
    registryDependencies: ["@coss/field", "@coss/number-field"],
    type: "registry:block",
  },
  {
    categories: categories(
      "field",
      "label",
      "form",
      "select",
      "checkbox",
      "button",
    ),
    description: "Complete form built with field",
    files: [{ path: "particles/particle-fd-18.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-fd-18",
    registryDependencies: [
      "@coss/field",
      "@coss/select",
      "@coss/checkbox",
      "@coss/form",
      "@coss/input",
      "@coss/button",
    ],
    type: "registry:block",
  },
  {
    categories: categories("fieldset"),
    description: "Fieldset with multiple fields",
    files: [{ path: "particles/particle-fs-1.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-fs-1",
    registryDependencies: ["@coss/fieldset", "@coss/field", "@coss/input"],
    type: "registry:block",
  },
  {
    categories: categories("form", "field", "button", "input"),
    description: "Input in a form",
    files: [{ path: "particles/particle-fm-1.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-fm-1",
    registryDependencies: [
      "@coss/form",
      "@coss/field",
      "@coss/button",
      "@coss/input",
    ],
    type: "registry:block",
  },
  {
    categories: categories(
      "form",
      "field",
      "button",
      "validation",
      "label",
      "zod",
    ),
    dependencies: ["zod"],
    description: "Form with zod validation",
    files: [{ path: "particles/particle-fm-2.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-fm-2",
    registryDependencies: [
      "@coss/form",
      "@coss/field",
      "@coss/button",
      "@coss/input",
    ],
    type: "registry:block",
  },
  {
    categories: categories("frame"),
    description: "Basic frame",
    files: [{ path: "particles/particle-fr-1.tsx", type: "registry:block" }],
    meta: {
      className: "**:data-[slot=preview]:w-full",
    },
    name: "particle-fr-1",
    registryDependencies: ["@coss/frame"],
    type: "registry:block",
  },
  {
    categories: categories("frame", "collapsible"),
    dependencies: ["lucide-react"],
    description: "Frame with collapsible content and delete button",
    files: [{ path: "particles/particle-fr-2.tsx", type: "registry:block" }],
    meta: {
      className: "**:data-[slot=preview]:w-full",
    },
    name: "particle-fr-2",
    registryDependencies: ["@coss/frame", "@coss/collapsible", "@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("kbd"),
    description: "Keyboard shortcuts display",
    files: [{ path: "particles/particle-kb-1.tsx", type: "registry:block" }],
    name: "particle-kb-1",
    registryDependencies: ["@coss/kbd"],
    type: "registry:block",
  },
  {
    categories: categories("group"),
    description: "Basic group",
    files: [{ path: "particles/particle-gp-1.tsx", type: "registry:block" }],
    name: "particle-gp-1",
    registryDependencies: ["@coss/group"],
    type: "registry:block",
  },
  {
    categories: categories("group", "input"),
    description: "Group with input",
    files: [{ path: "particles/particle-gp-2.tsx", type: "registry:block" }],
    name: "particle-gp-2",
    registryDependencies: ["@coss/group", "@coss/input"],
    type: "registry:block",
  },
  {
    categories: categories("group"),
    description: "Small group",
    files: [{ path: "particles/particle-gp-3.tsx", type: "registry:block" }],
    name: "particle-gp-3",
    registryDependencies: ["@coss/group"],
    type: "registry:block",
  },
  {
    categories: categories("group"),
    description: "Large group",
    files: [{ path: "particles/particle-gp-4.tsx", type: "registry:block" }],
    name: "particle-gp-4",
    registryDependencies: ["@coss/group"],
    type: "registry:block",
  },
  {
    categories: categories("group", "button"),
    description: "Group with disabled button",
    files: [{ path: "particles/particle-gp-5.tsx", type: "registry:block" }],
    name: "particle-gp-5",
    registryDependencies: ["@coss/group", "@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("group", "button"),
    description: "Group with default button",
    files: [{ path: "particles/particle-gp-6.tsx", type: "registry:block" }],
    name: "particle-gp-6",
    registryDependencies: ["@coss/group", "@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("group"),
    description: "Group with start text",
    files: [{ path: "particles/particle-gp-7.tsx", type: "registry:block" }],
    name: "particle-gp-7",
    registryDependencies: ["@coss/group"],
    type: "registry:block",
  },
  {
    categories: categories("group"),
    description: "Group with end text",
    files: [{ path: "particles/particle-gp-8.tsx", type: "registry:block" }],
    name: "particle-gp-8",
    registryDependencies: ["@coss/group"],
    type: "registry:block",
  },
  {
    categories: categories("group"),
    description: "Vertical group",
    files: [{ path: "particles/particle-gp-9.tsx", type: "registry:block" }],
    name: "particle-gp-9",
    registryDependencies: ["@coss/group"],
    type: "registry:block",
  },
  {
    categories: categories("group"),
    description: "Nested groups",
    files: [{ path: "particles/particle-gp-10.tsx", type: "registry:block" }],
    name: "particle-gp-10",
    registryDependencies: ["@coss/group"],
    type: "registry:block",
  },
  {
    categories: categories("group"),
    description: "Group with popup",
    files: [{ path: "particles/particle-gp-11.tsx", type: "registry:block" }],
    name: "particle-gp-11",
    registryDependencies: ["@coss/group"],
    type: "registry:block",
  },
  {
    categories: categories("group", "input group"),
    description: "Group with input group",
    files: [{ path: "particles/particle-gp-12.tsx", type: "registry:block" }],
    name: "particle-gp-12",
    registryDependencies: ["@coss/group", "@coss/input-group"],
    type: "registry:block",
  },
  {
    categories: categories("group", "menu"),
    description: "Group with menu",
    files: [{ path: "particles/particle-gp-13.tsx", type: "registry:block" }],
    name: "particle-gp-13",
    registryDependencies: ["@coss/group", "@coss/menu"],
    type: "registry:block",
  },
  {
    categories: categories("group", "select"),
    description: "Group with select",
    files: [{ path: "particles/particle-gp-14.tsx", type: "registry:block" }],
    name: "particle-gp-14",
    registryDependencies: ["@coss/group", "@coss/select"],
    type: "registry:block",
  },
  {
    categories: categories("input"),
    description: "Basic input",
    files: [{ path: "particles/particle-in-1.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-in-1",
    registryDependencies: ["@coss/input"],
    type: "registry:block",
  },
  {
    categories: categories("input"),
    description: "Small input",
    files: [{ path: "particles/particle-in-2.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-in-2",
    registryDependencies: ["@coss/input"],
    type: "registry:block",
  },
  {
    categories: categories("input"),
    description: "Large input",
    files: [{ path: "particles/particle-in-3.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-in-3",
    registryDependencies: ["@coss/input"],
    type: "registry:block",
  },
  {
    categories: categories("input"),
    description: "Disabled input",
    files: [{ path: "particles/particle-in-4.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-in-4",
    registryDependencies: ["@coss/input"],
    type: "registry:block",
  },
  {
    categories: categories("input"),
    description: "File input",
    files: [{ path: "particles/particle-in-5.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-in-5",
    registryDependencies: ["@coss/input"],
    type: "registry:block",
  },
  {
    categories: categories("input", "label"),
    description: "Input with label",
    files: [{ path: "particles/particle-in-6.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-in-6",
    registryDependencies: ["@coss/input", "@coss/label"],
    type: "registry:block",
  },
  {
    categories: categories("input", "button"),
    description: "Input with button",
    files: [{ path: "particles/particle-in-7.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-in-7",
    registryDependencies: ["@coss/input", "@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("input", "input group", "button", "popover"),
    description: "Input with start text and end tooltip",
    files: [{ path: "particles/particle-in-8.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-in-8",
    registryDependencies: [
      "@coss/button",
      "@coss/input-group",
      "@coss/popover",
    ],
    type: "registry:block",
  },
  {
    categories: categories("input", "input group", "button", "tooltip"),
    description: "Password input with toggle visibility",
    files: [{ path: "particles/particle-in-9.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-in-9",
    registryDependencies: [
      "@coss/button",
      "@coss/input-group",
      "@coss/tooltip",
    ],
    type: "registry:block",
  },
  {
    categories: categories("input", "input group", "button", "popover"),
    description: "Input group mimicking a URL bar",
    files: [{ path: "particles/particle-in-10.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-in-10",
    registryDependencies: [
      "@coss/button",
      "@coss/input-group",
      "@coss/popover",
    ],
    type: "registry:block",
  },
  {
    categories: categories("input", "input group", "kbd", "search"),
    description: "Input group with keyboard shortcut",
    files: [{ path: "particles/particle-in-11.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-in-11",
    registryDependencies: ["@coss/input-group", "@coss/kbd"],
    type: "registry:block",
  },
  {
    categories: categories("input", "input group", "loading", "spinner"),
    description: "Input group with start loading spinner",
    files: [{ path: "particles/particle-in-12.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-in-12",
    registryDependencies: ["@coss/input-group", "@coss/spinner"],
    type: "registry:block",
  },
  {
    categories: categories("input group"),
    description: "Basic input group",
    files: [{ path: "particles/particle-ig-1.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-ig-1",
    registryDependencies: ["@coss/input-group", "@coss/input"],
    type: "registry:block",
  },
  {
    categories: categories("input group"),
    dependencies: ["lucide-react"],
    description: "Input group with end icon",
    files: [{ path: "particles/particle-ig-2.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-ig-2",
    registryDependencies: ["@coss/input-group", "@coss/input"],
    type: "registry:block",
  },
  {
    categories: categories("input group"),
    description: "Input group with start text",
    files: [{ path: "particles/particle-ig-3.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-ig-3",
    registryDependencies: ["@coss/input-group", "@coss/input"],
    type: "registry:block",
  },
  {
    categories: categories("input group"),
    description: "Input group with end text",
    files: [{ path: "particles/particle-ig-4.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-ig-4",
    registryDependencies: ["@coss/input-group", "@coss/input"],
    type: "registry:block",
  },
  {
    categories: categories("input group"),
    description: "Input group with start and end text",
    files: [{ path: "particles/particle-ig-5.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-ig-5",
    registryDependencies: ["@coss/input-group", "@coss/input"],
    type: "registry:block",
  },
  {
    categories: categories("input group", "number field"),
    description: "Input group with number field",
    files: [{ path: "particles/particle-ig-6.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-ig-6",
    registryDependencies: ["@coss/input-group", "@coss/number-field"],
    type: "registry:block",
  },
  {
    categories: categories("input group", "tooltip"),
    dependencies: ["lucide-react"],
    description: "Input group with end tooltip",
    files: [{ path: "particles/particle-ig-7.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-ig-7",
    registryDependencies: ["@coss/input-group", "@coss/input", "@coss/tooltip"],
    type: "registry:block",
  },
  {
    categories: categories("input group", "button"),
    dependencies: ["lucide-react"],
    description: "Input group with icon button",
    files: [{ path: "particles/particle-ig-8.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-ig-8",
    registryDependencies: ["@coss/input-group", "@coss/input", "@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("input group", "button"),
    description: "Input group with button",
    files: [{ path: "particles/particle-ig-9.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-ig-9",
    registryDependencies: ["@coss/input-group", "@coss/input", "@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("input group", "badge"),
    description: "Input group with badge",
    files: [{ path: "particles/particle-ig-10.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-ig-10",
    registryDependencies: ["@coss/input-group", "@coss/input", "@coss/badge"],
    type: "registry:block",
  },
  {
    categories: categories("input group", "kbd"),
    description: "Input group with keyboard shortcut",
    files: [{ path: "particles/particle-ig-11.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-ig-11",
    registryDependencies: ["@coss/input-group", "@coss/input", "@coss/kbd"],
    type: "registry:block",
  },
  {
    categories: categories("input group", "label"),
    description: "Input group with inner label",
    files: [{ path: "particles/particle-ig-12.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-ig-12",
    registryDependencies: ["@coss/input-group", "@coss/input", "@coss/label"],
    type: "registry:block",
  },
  {
    categories: categories("input group"),
    description: "Small input group",
    files: [{ path: "particles/particle-ig-13.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-ig-13",
    registryDependencies: ["@coss/input-group", "@coss/input"],
    type: "registry:block",
  },
  {
    categories: categories("input group"),
    description: "Large input group",
    files: [{ path: "particles/particle-ig-14.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-ig-14",
    registryDependencies: ["@coss/input-group", "@coss/input"],
    type: "registry:block",
  },
  {
    categories: categories("input group"),
    description: "Disabled input group",
    files: [{ path: "particles/particle-ig-15.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-ig-15",
    registryDependencies: ["@coss/input-group", "@coss/input"],
    type: "registry:block",
  },
  {
    categories: categories("input group", "spinner"),
    description: "Input group with loading spinner",
    files: [{ path: "particles/particle-ig-16.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-ig-16",
    registryDependencies: ["@coss/input-group", "@coss/input", "@coss/spinner"],
    type: "registry:block",
  },
  {
    categories: categories("input group", "textarea"),
    description: "Input group with textarea",
    files: [{ path: "particles/particle-ig-17.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-80",
    },
    name: "particle-ig-17",
    registryDependencies: ["@coss/input-group", "@coss/textarea"],
    type: "registry:block",
  },
  {
    categories: categories("meter"),
    description: "Basic meter",
    files: [{ path: "particles/particle-mt-1.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-mt-1",
    registryDependencies: ["@coss/meter"],
    type: "registry:block",
  },
  {
    categories: categories("meter"),
    description: "Simple meter",
    files: [{ path: "particles/particle-mt-2.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-mt-2",
    registryDependencies: ["@coss/meter"],
    type: "registry:block",
  },
  {
    categories: categories("meter"),
    description: "Meter with formatted value",
    files: [{ path: "particles/particle-mt-3.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-mt-3",
    registryDependencies: ["@coss/meter"],
    type: "registry:block",
  },
  {
    categories: categories("meter"),
    description: "Meter with range",
    files: [{ path: "particles/particle-mt-4.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-mt-4",
    registryDependencies: ["@coss/meter"],
    type: "registry:block",
  },
  {
    categories: categories("menu"),
    description: "Basic menu",
    files: [{ path: "particles/particle-mn-1.tsx", type: "registry:block" }],
    name: "particle-mn-1",
    registryDependencies: ["@coss/menu"],
    type: "registry:block",
  },
  {
    categories: categories("menu"),
    description: "Menu with hover",
    files: [{ path: "particles/particle-mn-2.tsx", type: "registry:block" }],
    name: "particle-mn-2",
    registryDependencies: ["@coss/menu"],
    type: "registry:block",
  },
  {
    categories: categories("menu"),
    description: "Menu with checkbox",
    files: [{ path: "particles/particle-mn-3.tsx", type: "registry:block" }],
    name: "particle-mn-3",
    registryDependencies: ["@coss/menu", "@coss/checkbox"],
    type: "registry:block",
  },
  {
    categories: categories("menu"),
    description: "Menu with radio group",
    files: [{ path: "particles/particle-mn-4.tsx", type: "registry:block" }],
    name: "particle-mn-4",
    registryDependencies: ["@coss/menu", "@coss/radio-group"],
    type: "registry:block",
  },
  {
    categories: categories("menu"),
    description: "Menu with link",
    files: [{ path: "particles/particle-mn-5.tsx", type: "registry:block" }],
    name: "particle-mn-5",
    registryDependencies: ["@coss/menu"],
    type: "registry:block",
  },
  {
    categories: categories("menu"),
    description: "Menu with group labels",
    files: [{ path: "particles/particle-mn-6.tsx", type: "registry:block" }],
    name: "particle-mn-6",
    registryDependencies: ["@coss/menu"],
    type: "registry:block",
  },
  {
    categories: categories("menu"),
    description: "Nested menu",
    files: [{ path: "particles/particle-mn-7.tsx", type: "registry:block" }],
    name: "particle-mn-7",
    registryDependencies: ["@coss/menu"],
    type: "registry:block",
  },
  {
    categories: categories("menu"),
    description: "Menu close on click",
    files: [{ path: "particles/particle-mn-8.tsx", type: "registry:block" }],
    name: "particle-mn-8",
    registryDependencies: ["@coss/menu"],
    type: "registry:block",
  },
  {
    categories: categories("number field"),
    description: "Basic number field",
    files: [{ path: "particles/particle-nf-1.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-nf-1",
    registryDependencies: ["@coss/number-field"],
    type: "registry:block",
  },
  {
    categories: categories("number field"),
    description: "Small number field",
    files: [{ path: "particles/particle-nf-2.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-nf-2",
    registryDependencies: ["@coss/number-field"],
    type: "registry:block",
  },
  {
    categories: categories("number field"),
    description: "Large number field",
    files: [{ path: "particles/particle-nf-3.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-nf-3",
    registryDependencies: ["@coss/number-field"],
    type: "registry:block",
  },
  {
    categories: categories("number field"),
    description: "Disabled number field",
    files: [{ path: "particles/particle-nf-4.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-nf-4",
    registryDependencies: ["@coss/number-field"],
    type: "registry:block",
  },
  {
    categories: categories("number field"),
    description: "Number field with label",
    files: [{ path: "particles/particle-nf-5.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-nf-5",
    registryDependencies: ["@coss/number-field", "@coss/label"],
    type: "registry:block",
  },
  {
    categories: categories("number field"),
    description: "Number field with scrub",
    files: [{ path: "particles/particle-nf-6.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-nf-6",
    registryDependencies: ["@coss/number-field"],
    type: "registry:block",
  },
  {
    categories: categories("number field"),
    description: "Number field with range",
    files: [{ path: "particles/particle-nf-7.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-nf-7",
    registryDependencies: ["@coss/number-field"],
    type: "registry:block",
  },
  {
    categories: categories("number field"),
    description: "Number field with formatted value",
    files: [{ path: "particles/particle-nf-8.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-nf-8",
    registryDependencies: ["@coss/number-field"],
    type: "registry:block",
  },
  {
    categories: categories("number field"),
    description: "Number field with step",
    files: [{ path: "particles/particle-nf-9.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-nf-9",
    registryDependencies: ["@coss/number-field"],
    type: "registry:block",
  },
  {
    categories: categories("number field"),
    description: "Number field in form",
    files: [{ path: "particles/particle-nf-10.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-nf-10",
    registryDependencies: ["@coss/number-field", "@coss/form", "@coss/field"],
    type: "registry:block",
  },
  {
    categories: categories("pagination"),
    description: "Pagination example",
    files: [{ path: "particles/particle-pg-1.tsx", type: "registry:block" }],
    name: "particle-pg-1",
    registryDependencies: ["@coss/pagination"],
    type: "registry:block",
  },
  {
    categories: categories("pagination"),
    description: "Pagination with previous and next buttons only",
    files: [{ path: "particles/particle-pg-2.tsx", type: "registry:block" }],
    meta: {
      className: "**:data-[slot=preview]:w-full",
    },
    name: "particle-pg-2",
    registryDependencies: ["@coss/pagination"],
    type: "registry:block",
  },
  {
    categories: categories("pagination", "select"),
    description: "Pagination with select, and previous and next buttons",
    files: [{ path: "particles/particle-pg-3.tsx", type: "registry:block" }],
    meta: {
      className: "**:data-[slot=preview]:w-full",
    },
    name: "particle-pg-3",
    registryDependencies: ["@coss/pagination", "@coss/select"],
    type: "registry:block",
  },
  {
    categories: categories("popover", "button", "textarea", "form", "field"),
    description: "Popover with a form",
    files: [{ path: "particles/particle-po-1.tsx", type: "registry:block" }],
    name: "particle-po-1",
    registryDependencies: [
      "@coss/popover",
      "@coss/button",
      "@coss/textarea",
      "@coss/form",
      "@coss/field",
    ],
    type: "registry:block",
  },
  {
    categories: categories("popover", "button"),
    dependencies: ["lucide-react"],
    description: "Popover with close button",
    files: [{ path: "particles/particle-po-2.tsx", type: "registry:block" }],
    name: "particle-po-2",
    registryDependencies: ["@coss/popover", "@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("preview card"),
    dependencies: ["lucide-react"],
    description: "Preview card with popup",
    files: [{ path: "particles/particle-pc-1.tsx", type: "registry:block" }],
    name: "particle-pc-1",
    registryDependencies: ["@coss/preview-card", "@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("progress"),
    description: "Basic progress bar",
    files: [{ path: "particles/particle-pr-1.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-pr-1",
    registryDependencies: ["@coss/progress"],
    type: "registry:block",
  },
  {
    categories: categories("progress"),
    description: "Progress with label and value",
    files: [{ path: "particles/particle-pr-2.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-pr-2",
    registryDependencies: ["@coss/progress"],
    type: "registry:block",
  },
  {
    categories: categories("progress"),
    description: "Progress with formatted value",
    files: [{ path: "particles/particle-pr-3.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-pr-3",
    registryDependencies: ["@coss/progress"],
    type: "registry:block",
  },
  {
    categories: categories("radio group"),
    description: "Basic radio group",
    files: [{ path: "particles/particle-rg-1.tsx", type: "registry:block" }],
    name: "particle-rg-1",
    registryDependencies: ["@coss/radio-group"],
    type: "registry:block",
  },
  {
    categories: categories("radio group"),
    description: "Disabled radio group",
    files: [{ path: "particles/particle-rg-2.tsx", type: "registry:block" }],
    name: "particle-rg-2",
    registryDependencies: ["@coss/radio-group"],
    type: "registry:block",
  },
  {
    categories: categories("radio group"),
    description: "Radio group with description",
    files: [{ path: "particles/particle-rg-3.tsx", type: "registry:block" }],
    name: "particle-rg-3",
    registryDependencies: ["@coss/radio-group"],
    type: "registry:block",
  },
  {
    categories: categories("radio group"),
    description: "Radio group card",
    files: [{ path: "particles/particle-rg-4.tsx", type: "registry:block" }],
    name: "particle-rg-4",
    registryDependencies: ["@coss/radio-group", "@coss/card"],
    type: "registry:block",
  },
  {
    categories: categories("radio group"),
    description: "Radio group in form",
    files: [{ path: "particles/particle-rg-5.tsx", type: "registry:block" }],
    name: "particle-rg-5",
    registryDependencies: ["@coss/radio-group", "@coss/form", "@coss/field"],
    type: "registry:block",
  },
  {
    categories: categories("scroll area"),
    description: "Basic scroll area",
    files: [{ path: "particles/particle-sa-1.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-sa-1",
    registryDependencies: ["@coss/scroll-area"],
    type: "registry:block",
  },
  {
    categories: categories("scroll area"),
    description: "Horizontal scroll area",
    files: [{ path: "particles/particle-sa-2.tsx", type: "registry:block" }],
    name: "particle-sa-2",
    registryDependencies: ["@coss/scroll-area"],
    type: "registry:block",
  },
  {
    categories: categories("scroll area"),
    description: "Scroll area with both directions",
    files: [{ path: "particles/particle-sa-3.tsx", type: "registry:block" }],
    name: "particle-sa-3",
    registryDependencies: ["@coss/scroll-area"],
    type: "registry:block",
  },
  {
    categories: categories("select"),
    description: "Basic select",
    files: [{ path: "particles/particle-sl-1.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-sl-1",
    registryDependencies: ["@coss/select"],
    type: "registry:block",
  },
  {
    categories: categories("select"),
    description: "Small select",
    files: [{ path: "particles/particle-sl-2.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-sl-2",
    registryDependencies: ["@coss/select"],
    type: "registry:block",
  },
  {
    categories: categories("select"),
    description: "Large select",
    files: [{ path: "particles/particle-sl-3.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-sl-3",
    registryDependencies: ["@coss/select"],
    type: "registry:block",
  },
  {
    categories: categories("select"),
    description: "Disabled select",
    files: [{ path: "particles/particle-sl-4.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-sl-4",
    registryDependencies: ["@coss/select"],
    type: "registry:block",
  },
  {
    categories: categories("select"),
    description: "Select without item alignment",
    files: [{ path: "particles/particle-sl-5.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-sl-5",
    registryDependencies: ["@coss/select"],
    type: "registry:block",
  },
  {
    categories: categories("select"),
    description: "Select with groups",
    files: [{ path: "particles/particle-sl-6.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-sl-6",
    registryDependencies: ["@coss/select"],
    type: "registry:block",
  },
  {
    categories: categories("select"),
    description: "Multiple select",
    files: [{ path: "particles/particle-sl-7.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-sl-7",
    registryDependencies: ["@coss/select"],
    type: "registry:block",
  },
  {
    categories: categories("select"),
    dependencies: ["lucide-react"],
    description: "Select with icon",
    files: [{ path: "particles/particle-sl-8.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-sl-8",
    registryDependencies: ["@coss/select"],
    type: "registry:block",
  },
  {
    categories: categories("select"),
    dependencies: ["lucide-react"],
    description: "Select options with icon",
    files: [{ path: "particles/particle-sl-9.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-sl-9",
    registryDependencies: ["@coss/select"],
    type: "registry:block",
  },
  {
    categories: categories("select"),
    description: "Select with object values",
    files: [{ path: "particles/particle-sl-10.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-sl-10",
    registryDependencies: ["@coss/select"],
    type: "registry:block",
  },
  {
    categories: categories("select"),
    description: "Select in form",
    files: [{ path: "particles/particle-sl-11.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-sl-11",
    registryDependencies: ["@coss/select", "@coss/form", "@coss/field"],
    type: "registry:block",
  },
  {
    categories: categories("separator"),
    description: "Separator with horizontal and vertical orientations",
    files: [{ path: "particles/particle-sp-1.tsx", type: "registry:block" }],
    name: "particle-sp-1",
    registryDependencies: ["@coss/separator"],
    type: "registry:block",
  },
  {
    categories: categories("sheet"),
    description: "Basic sheet",
    files: [{ path: "particles/particle-sh-1.tsx", type: "registry:block" }],
    name: "particle-sh-1",
    registryDependencies: [
      "@coss/sheet",
      "@coss/button",
      "@coss/form",
      "@coss/field",
      "@coss/input",
    ],
    type: "registry:block",
  },
  {
    categories: categories("sheet"),
    description: "Sheet inset",
    files: [{ path: "particles/particle-sh-2.tsx", type: "registry:block" }],
    name: "particle-sh-2",
    registryDependencies: ["@coss/sheet", "@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("sheet"),
    description: "Sheet position",
    files: [{ path: "particles/particle-sh-3.tsx", type: "registry:block" }],
    name: "particle-sh-3",
    registryDependencies: ["@coss/sheet", "@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("skeleton"),
    description: "Basic skeleton",
    files: [{ path: "particles/particle-sk-1.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:flex **:data-[slot=preview]:justify-center",
    },
    name: "particle-sk-1",
    registryDependencies: ["@coss/skeleton"],
    type: "registry:block",
  },
  {
    categories: categories("skeleton"),
    description: "Skeleton only",
    files: [{ path: "particles/particle-sk-2.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:flex **:data-[slot=preview]:justify-center",
    },
    name: "particle-sk-2",
    registryDependencies: ["@coss/skeleton"],
    type: "registry:block",
  },
  {
    categories: categories("slider"),
    description: "Basic slider",
    files: [{ path: "particles/particle-sd-1.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-sd-1",
    registryDependencies: ["@coss/slider"],
    type: "registry:block",
  },
  {
    categories: categories("slider"),
    description: "Slider with label and value",
    files: [{ path: "particles/particle-sd-2.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-sd-2",
    registryDependencies: ["@coss/slider"],
    type: "registry:block",
  },
  {
    categories: categories("slider"),
    description: "Range slider",
    files: [{ path: "particles/particle-sd-3.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-sd-3",
    registryDependencies: ["@coss/slider"],
    type: "registry:block",
  },
  {
    categories: categories("slider"),
    description: "Vertical slider",
    files: [{ path: "particles/particle-sd-4.tsx", type: "registry:block" }],
    name: "particle-sd-4",
    registryDependencies: ["@coss/slider"],
    type: "registry:block",
  },
  {
    categories: categories("slider"),
    description: "Slider in form",
    files: [{ path: "particles/particle-sd-5.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-sd-5",
    registryDependencies: ["@coss/slider", "@coss/form", "@coss/field"],
    type: "registry:block",
  },
  {
    categories: categories("spinner"),
    description: "Basic spinner",
    files: [{ path: "particles/particle-sn-1.tsx", type: "registry:block" }],
    name: "particle-sn-1",
    registryDependencies: ["@coss/spinner"],
    type: "registry:block",
  },
  {
    categories: categories("switch"),
    description: "Basic switch",
    files: [{ path: "particles/particle-sw-1.tsx", type: "registry:block" }],
    name: "particle-sw-1",
    registryDependencies: ["@coss/switch"],
    type: "registry:block",
  },
  {
    categories: categories("switch"),
    description: "Disabled switch",
    files: [{ path: "particles/particle-sw-2.tsx", type: "registry:block" }],
    name: "particle-sw-2",
    registryDependencies: ["@coss/switch"],
    type: "registry:block",
  },
  {
    categories: categories("switch"),
    description: "Switch with description",
    files: [{ path: "particles/particle-sw-3.tsx", type: "registry:block" }],
    name: "particle-sw-3",
    registryDependencies: ["@coss/switch"],
    type: "registry:block",
  },
  {
    categories: categories("switch"),
    description: "Switch card",
    files: [{ path: "particles/particle-sw-4.tsx", type: "registry:block" }],
    name: "particle-sw-4",
    registryDependencies: ["@coss/switch", "@coss/card"],
    type: "registry:block",
  },
  {
    categories: categories("switch"),
    description: "Switch in form",
    files: [{ path: "particles/particle-sw-5.tsx", type: "registry:block" }],
    name: "particle-sw-5",
    registryDependencies: ["@coss/switch", "@coss/form", "@coss/field"],
    type: "registry:block",
  },
  {
    categories: categories("table"),
    description: "Basic table",
    files: [{ path: "particles/particle-ta-1.tsx", type: "registry:block" }],
    meta: {
      className: "**:data-[slot=preview]:w-full",
    },
    name: "particle-ta-1",
    registryDependencies: ["@coss/table"],
    type: "registry:block",
  },
  {
    categories: categories("table"),
    description: "Framed table",
    files: [{ path: "particles/particle-ta-2.tsx", type: "registry:block" }],
    meta: {
      className: "**:data-[slot=preview]:w-full",
    },
    name: "particle-ta-2",
    registryDependencies: ["@coss/table"],
    type: "registry:block",
  },
  {
    categories: categories("tabs"),
    description: "Basic tabs",
    files: [{ path: "particles/particle-tb-1.tsx", type: "registry:block" }],
    name: "particle-tb-1",
    registryDependencies: ["@coss/tabs"],
    type: "registry:block",
  },
  {
    categories: categories("tabs"),
    description: "Tabs with underline",
    files: [{ path: "particles/particle-tb-2.tsx", type: "registry:block" }],
    name: "particle-tb-2",
    registryDependencies: ["@coss/tabs"],
    type: "registry:block",
  },
  {
    categories: categories("tabs"),
    description: "Vertical tabs",
    files: [{ path: "particles/particle-tb-3.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full sm:**:data-[slot=preview]:max-w-80",
    },
    name: "particle-tb-3",
    registryDependencies: ["@coss/tabs"],
    type: "registry:block",
  },
  {
    categories: categories("tabs"),
    description: "Vertical tabs with underline",
    files: [{ path: "particles/particle-tb-4.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full sm:**:data-[slot=preview]:max-w-80",
    },
    name: "particle-tb-4",
    registryDependencies: ["@coss/tabs"],
    type: "registry:block",
  },
  {
    categories: categories("textarea"),
    description: "Basic textarea",
    files: [{ path: "particles/particle-tx-1.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-tx-1",
    registryDependencies: ["@coss/textarea"],
    type: "registry:block",
  },
  {
    categories: categories("textarea"),
    description: "Small textarea",
    files: [{ path: "particles/particle-tx-2.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-tx-2",
    registryDependencies: ["@coss/textarea"],
    type: "registry:block",
  },
  {
    categories: categories("textarea"),
    description: "Large textarea",
    files: [{ path: "particles/particle-tx-3.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-tx-3",
    registryDependencies: ["@coss/textarea"],
    type: "registry:block",
  },
  {
    categories: categories("textarea"),
    description: "Disabled textarea",
    files: [{ path: "particles/particle-tx-4.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-tx-4",
    registryDependencies: ["@coss/textarea"],
    type: "registry:block",
  },
  {
    categories: categories("textarea"),
    description: "Textarea with label",
    files: [{ path: "particles/particle-tx-5.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-tx-5",
    registryDependencies: ["@coss/textarea", "@coss/label"],
    type: "registry:block",
  },
  {
    categories: categories("textarea"),
    description: "Textarea in form",
    files: [{ path: "particles/particle-tx-6.tsx", type: "registry:block" }],
    meta: {
      className:
        "**:data-[slot=preview]:w-full **:data-[slot=preview]:max-w-64",
    },
    name: "particle-tx-6",
    registryDependencies: ["@coss/textarea", "@coss/form", "@coss/field"],
    type: "registry:block",
  },
  {
    categories: categories("toast"),
    description: "Basic toast",
    files: [{ path: "particles/particle-ts-1.tsx", type: "registry:block" }],
    name: "particle-ts-1",
    registryDependencies: ["@coss/toast"],
    type: "registry:block",
  },
  {
    categories: categories("toast"),
    description: "Toast with status",
    files: [{ path: "particles/particle-ts-2.tsx", type: "registry:block" }],
    name: "particle-ts-2",
    registryDependencies: ["@coss/toast"],
    type: "registry:block",
  },
  {
    categories: categories("toast"),
    description: "Loading toast",
    files: [{ path: "particles/particle-ts-3.tsx", type: "registry:block" }],
    name: "particle-ts-3",
    registryDependencies: ["@coss/toast"],
    type: "registry:block",
  },
  {
    categories: categories("toast"),
    description: "Toast with action",
    files: [{ path: "particles/particle-ts-4.tsx", type: "registry:block" }],
    name: "particle-ts-4",
    registryDependencies: ["@coss/toast", "@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("toast"),
    description: "Promise toast",
    files: [{ path: "particles/particle-ts-5.tsx", type: "registry:block" }],
    name: "particle-ts-5",
    registryDependencies: ["@coss/toast"],
    type: "registry:block",
  },
  {
    categories: categories("toast"),
    description: "Toast with varying heights",
    files: [{ path: "particles/particle-ts-6.tsx", type: "registry:block" }],
    name: "particle-ts-6",
    registryDependencies: ["@coss/toast"],
    type: "registry:block",
  },
  {
    categories: categories("toggle", "toggle group"),
    description: "Basic toggle group",
    files: [{ path: "particles/particle-tg-1.tsx", type: "registry:block" }],
    name: "particle-tg-1",
    registryDependencies: ["@coss/toggle-group"],
    type: "registry:block",
  },
  {
    categories: categories("toggle", "toggle group"),
    description: "Small toggle group",
    files: [{ path: "particles/particle-tg-2.tsx", type: "registry:block" }],
    name: "particle-tg-2",
    registryDependencies: ["@coss/toggle-group"],
    type: "registry:block",
  },
  {
    categories: categories("toggle", "toggle group"),
    description: "Large toggle group",
    files: [{ path: "particles/particle-tg-3.tsx", type: "registry:block" }],
    name: "particle-tg-3",
    registryDependencies: ["@coss/toggle-group"],
    type: "registry:block",
  },
  {
    categories: categories("toggle", "toggle group"),
    description: "Toggle group with outline",
    files: [{ path: "particles/particle-tg-4.tsx", type: "registry:block" }],
    name: "particle-tg-4",
    registryDependencies: ["@coss/toggle-group"],
    type: "registry:block",
  },
  {
    categories: categories("toggle", "toggle group"),
    description: "Vertical toggle group with outline",
    files: [{ path: "particles/particle-tg-5.tsx", type: "registry:block" }],
    name: "particle-tg-5",
    registryDependencies: ["@coss/toggle-group"],
    type: "registry:block",
  },
  {
    categories: categories("toggle", "toggle group"),
    description: "Disabled toggle group",
    files: [{ path: "particles/particle-tg-6.tsx", type: "registry:block" }],
    name: "particle-tg-6",
    registryDependencies: ["@coss/toggle-group"],
    type: "registry:block",
  },
  {
    categories: categories("toggle", "toggle group"),
    description: "Toggle group with disabled item",
    files: [{ path: "particles/particle-tg-7.tsx", type: "registry:block" }],
    name: "particle-tg-7",
    registryDependencies: ["@coss/toggle-group"],
    type: "registry:block",
  },
  {
    categories: categories("toggle", "toggle group"),
    description: "Multiple selection toggle group",
    files: [{ path: "particles/particle-tg-8.tsx", type: "registry:block" }],
    name: "particle-tg-8",
    registryDependencies: ["@coss/toggle-group"],
    type: "registry:block",
  },
  {
    categories: categories("toggle"),
    description: "Basic toggle",
    files: [{ path: "particles/particle-to-1.tsx", type: "registry:block" }],
    name: "particle-to-1",
    registryDependencies: ["@coss/toggle"],
    type: "registry:block",
  },
  {
    categories: categories("toggle"),
    description: "Toggle with outline",
    files: [{ path: "particles/particle-to-2.tsx", type: "registry:block" }],
    name: "particle-to-2",
    registryDependencies: ["@coss/toggle"],
    type: "registry:block",
  },
  {
    categories: categories("toggle"),
    dependencies: ["lucide-react"],
    description: "Toggle with icon",
    files: [{ path: "particles/particle-to-3.tsx", type: "registry:block" }],
    name: "particle-to-3",
    registryDependencies: ["@coss/toggle"],
    type: "registry:block",
  },
  {
    categories: categories("toggle"),
    description: "Small toggle",
    files: [{ path: "particles/particle-to-4.tsx", type: "registry:block" }],
    name: "particle-to-4",
    registryDependencies: ["@coss/toggle"],
    type: "registry:block",
  },
  {
    categories: categories("toggle"),
    description: "Large toggle",
    files: [{ path: "particles/particle-to-5.tsx", type: "registry:block" }],
    name: "particle-to-5",
    registryDependencies: ["@coss/toggle"],
    type: "registry:block",
  },
  {
    categories: categories("toggle"),
    description: "Disabled toggle",
    files: [{ path: "particles/particle-to-6.tsx", type: "registry:block" }],
    name: "particle-to-6",
    registryDependencies: ["@coss/toggle"],
    type: "registry:block",
  },
  {
    categories: categories("toggle"),
    dependencies: ["lucide-react"],
    description: "Toggle icon group",
    files: [{ path: "particles/particle-to-7.tsx", type: "registry:block" }],
    name: "particle-to-7",
    registryDependencies: ["@coss/toggle"],
    type: "registry:block",
  },
  {
    categories: categories("toolbar"),
    dependencies: ["lucide-react"],
    description: "Toolbar with toggles, buttons, and select",
    files: [{ path: "particles/particle-tr-1.tsx", type: "registry:block" }],
    name: "particle-tr-1",
    registryDependencies: [
      "@coss/toolbar",
      "@coss/toggle-group",
      "@coss/button",
      "@coss/select",
      "@coss/tooltip",
    ],
    type: "registry:block",
  },
  {
    categories: categories("tooltip"),
    description: "Basic tooltip",
    files: [{ path: "particles/particle-tt-1.tsx", type: "registry:block" }],
    name: "particle-tt-1",
    registryDependencies: ["@coss/tooltip", "@coss/button"],
    type: "registry:block",
  },
  {
    categories: categories("tooltip"),
    description: "Grouped tooltips",
    files: [{ path: "particles/particle-tt-2.tsx", type: "registry:block" }],
    name: "particle-tt-2",
    registryDependencies: ["@coss/tooltip", "@coss/button"],
    type: "registry:block",
  },
];
